= Ruoli applicazione
:allow-uri-read: 




== Ruoli applicazione

I ruoli delle applicazioni forniscono l'accesso alle applicazioni BlueXP  come il consulente digitale Active IQ (noto anche come consulente digitale).



=== Amministratore dello storage

Fornisce all'utente la possibilità di eseguire funzioni di amministrazione dello storage in BlueXP , come aggiornamenti software e creazione ed eliminazione di ambienti di lavoro BlueXP .

Permessi:: Può visualizzare BlueXP  Canvas. Può creare e gestire connettori BlueXP . Dispone dell'accesso in lettura/scrittura alle funzioni di salute e governance dello storage di BlueXP , tra cui:
+
--
* Consulente digitale
* Resilienza operativa
* Aggiornamenti software (possono eseguire aggiornamenti software)
* Portafoglio digitale
* Efficienza economica
* Dashboard sulla sostenibilità
* Avvisi


--




=== Visualizzatore di archiviazione

Fornisce accesso di sola lettura alle funzioni di salute e governance di BlueXP . Questo ruolo viene generalmente assegnato agli utenti responsabili del monitoraggio dello stato delle risorse di archiviazione di un'organizzazione. Gli utenti con questo ruolo possono vedere più applicazioni all'interno di BlueXP  per creare piani di aggiornamento software, piani per l'efficienza e visualizzare lo stato generale dello storage.

Permessi:: Dispone di accesso in sola lettura alle funzioni di governance e salute dello storage di BlueXP , tra cui:
+
--
* Consulente digitale
* Resilienza operativa
* Aggiornamenti software (possono scaricare i piani di aggiornamento)
* Portafoglio digitale
* Efficienza economica
* Dashboard sulla sostenibilità
* Avvisi


--


Esempio dell'attività: Ad esempio, se nella gerarchia delle risorse sono presenti sette progetti che rappresentano i rispettivi ambienti di lavoro, è possibile assegnare a un utente il ruolo di amministratore dello storage per tre dei progetti e quindi assegnare a un altro membro l'amministratore dello storage per i progetti rimanenti. Un'altra possibilità potrebbe essere quella di assegnare a un utente il ruolo di amministratore dello storage per l'intera organizzazione. È possibile gestire i ruoli dei membri in base alle esigenze dell'organizzazione.
