---
sidebar: sidebar 
permalink: concept-install-options-azure.html 
keywords: install connector azure, azure install connector, connector azure, azure connector, installation options, azure marketplace, manual install 
summary: Esistono diversi modi per creare un connettore in Azure. Direttamente da BlueXP è il modo più comune. 
---
= Opzioni di installazione del connettore in Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Esistono diversi modi per creare un connettore in Azure. Direttamente da BlueXP è il modo più comune.

Sono disponibili le seguenti opzioni di installazione:

* link:task-install-connector-azure-bluexp.html["Crea un connettore direttamente da BlueXP"] (questa è l'opzione standard)
+
Questa azione avvia una macchina virtuale che esegue Linux e il software del connettore in un VNET a scelta.

* link:task-install-connector-azure-marketplace.html["Creare un connettore da Azure Marketplace"]
+
Questa azione avvia anche una macchina virtuale con Linux e il software Connector, ma l'implementazione viene avviata direttamente da Azure Marketplace e non da BlueXP.

* link:task-install-connector-azure-manual.html["Scaricare e installare manualmente il software sul proprio host Linux"]


L'opzione di installazione scelta influisce sul modo in cui si prepara l'installazione. Ciò include il modo in cui si forniscono a BlueXP le autorizzazioni necessarie per autenticare e gestire le risorse in Azure.
