---
sidebar: sidebar 
permalink: concept-connectors.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery' 
summary: 'Un connettore è il software NetApp in esecuzione nella rete cloud o on-premise. Esegue le azioni che BlueXP deve eseguire per gestire l"infrastruttura dati. Il connettore esegue costantemente il polling del livello BlueXP SaaS per individuare eventuali azioni da intraprendere. Non è necessario un connettore per iniziare a utilizzare BlueXP, ma è necessario creare un connettore per sbloccare tutte le funzionalità e i servizi di BlueXP.' 
---
= Scopri di più sui connettori
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Un _connettore_ è il software NetApp in esecuzione nella rete cloud o on-premise. Esegue le azioni che BlueXP deve eseguire per gestire l'infrastruttura dati. Il connettore esegue costantemente il polling del livello BlueXP SaaS per individuare eventuali azioni da intraprendere. Non è necessario un connettore per iniziare a utilizzare BlueXP, ma è necessario creare un connettore per sbloccare tutte le funzionalità e i servizi di BlueXP.



== Cosa puoi fare senza un connettore

Non è necessario un connettore per iniziare a utilizzare BlueXP. È possibile utilizzare diverse funzionalità e servizi in BlueXP senza creare alcun connettore.

È possibile utilizzare le seguenti funzionalità e servizi BlueXP senza un connettore:

* Creazione dell'ambiente di lavoro Amazon FSX per NetApp ONTAP
+
Sebbene non sia necessario un connettore per creare un ambiente di lavoro, è necessario creare e gestire volumi, replicare i dati e integrare FSX per ONTAP con servizi come la classificazione BlueXP e la copia e la sincronizzazione BlueXP.

* Catalogo di automazione
* Azure NetApp Files
+
Sebbene non sia necessario un connettore per configurare e gestire Azure NetApp Files, è necessario un connettore per utilizzare la classificazione BlueXP per eseguire la scansione dei dati Azure NetApp Files.

* Cloud Volumes Service per Google Cloud
* Copia e sincronizzazione
* Consulente digitale
* Portafoglio digitale
+
In quasi tutti i casi, è possibile aggiungere una licenza al portafoglio digitale senza un connettore.

+
Per aggiungere una licenza al portafoglio digitale è necessario un connettore solo per le licenze Cloud Volumes ONTAP _basate su nodo_. In questo caso, è necessario un connettore perché i dati provengono dalle licenze installate sui sistemi Cloud Volumes ONTAP.

* Rilevamento diretto dei cluster ONTAP on-premise
+
Sebbene non sia necessario un connettore per il rilevamento diretto di un cluster ONTAP on-premise, è necessario un connettore per sfruttare le funzionalità aggiuntive di BlueXP.

+
https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["Scopri di più sulle opzioni di rilevamento e gestione dei cluster ONTAP on-premise"^]

* Aggiornamenti software
* Sostenibilità




== Quando è necessario un connettore

Quando si utilizza BlueXP in modalità standard, è necessario un connettore per le seguenti funzionalità e servizi in BlueXP:

* Avvisi
* Funzionalità di gestione di Amazon FSX per ONTAP
* Storage Amazon S3
* Storage Azure Blob
* Backup e recovery
* Classificazione
* Cloud Volumes ONTAP
* Disaster recovery
* Sistemi e-Series
* Efficienza economica ^1^
* Bucket di storage Google Cloud
* Integrazione del cluster ONTAP on-premise con i servizi dati BlueXP
* Resilienza operativa ^1^
* Protezione ransomware
* Sistemi StorageGRID
* Tiering
* Caching dei volumi


^1^ sebbene sia possibile accedere a questi servizi senza un connettore, è necessario un connettore per avviare azioni dai servizi.

Per utilizzare BlueXP in modalità limitata o privata è necessario un connettore.



== I connettori devono essere sempre operativi

I connettori sono una parte fondamentale dell'architettura del servizio BlueXP. È tua responsabilità garantire che i connettori pertinenti siano sempre attivi, operativi e accessibili. Sebbene il servizio sia progettato per superare brevi interruzioni della disponibilità del connettore, è necessario intraprendere azioni immediate quando è necessario rimediare ai guasti dell'infrastruttura.

La presente documentazione è disciplinata dall'EULA. Se il prodotto non viene utilizzato in conformità con la documentazione, la funzionalità e il funzionamento del prodotto, nonché i diritti dell'utente previsti dal Contratto di licenza con l'utente finale, potrebbero risentire negativamente.



=== Impatto su Cloud Volumes ONTAP

Un connettore è un componente chiave per lo stato e il funzionamento di Cloud Volumes ONTAP. Se un connettore viene spento, i sistemi PAYGO Cloud Volumes ONTAP e i sistemi BYOL basati sulla capacità si arrestano dopo aver perso la comunicazione con un connettore per più di 14 giorni. Questo accade perché il connettore aggiorna le licenze sul sistema ogni giorno.

Se il sistema Cloud Volumes ONTAP dispone di una licenza BYOL basata su nodo, il sistema rimane in esecuzione dopo 14 giorni perché la licenza è installata sul sistema Cloud Volumes ONTAP.



== Posizioni supportate

Un connettore è supportato nelle seguenti posizioni:

* Amazon Web Services
* Microsoft Azure
+
Un connettore in Azure deve essere implementato nella stessa regione di Azure dei sistemi Cloud Volumes ONTAP che gestisce o in https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Coppia di regioni Azure"^] Per i sistemi Cloud Volumes ONTAP. Questo requisito garantisce l'utilizzo di una connessione Azure Private link tra Cloud Volumes ONTAP e i relativi account di storage associati. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-enabling-private-link.html["Scopri come Cloud Volumes ONTAP utilizza un collegamento privato Azure"^]

* Google Cloud
+
Se si desidera utilizzare i servizi BlueXP con Google Cloud, è necessario utilizzare un connettore in esecuzione in Google Cloud.

* On-premise




== Comunicazioni con i cloud provider

Il connettore utilizza TLS 1,2 per tutte le comunicazioni con AWS, Azure e Google Cloud.



== Modalità limitata e modalità privata

Per utilizzare BlueXP in modalità limitata o privata, è possibile iniziare a utilizzare BlueXP installando il connettore e accedendo all'interfaccia utente in esecuzione localmente sul connettore.

link:concept-modes.html["Scopri le modalità di implementazione di BlueXP"].



== Come creare un connettore

Puoi creare un connettore direttamente da BlueXP , dal marketplace del tuo cloud provider o installando manualmente il software sul tuo host Linux. Il modo in cui iniziare dipende dall'utilizzo di BlueXP in modalità standard, limitata o privata.

* link:concept-modes.html["Scopri le modalità di implementazione di BlueXP"]
* link:task-quick-start-standard-mode.html["Inizia subito con BlueXP in modalità standard"]
* link:task-quick-start-restricted-mode.html["Inizia subito con BlueXP in modalità limitata"]
* link:task-quick-start-private-mode.html["Inizia subito con BlueXP in modalità privata"]




== Permessi

Sono necessarie autorizzazioni specifiche per creare il connettore direttamente da BlueXP e un altro set di autorizzazioni per l'istanza del connettore stesso. Se si crea il connettore in AWS o Azure direttamente da BlueXP, BlueXP crea il connettore con le autorizzazioni necessarie.

Quando si utilizza BlueXP in modalità standard, il modo in cui si forniscono le autorizzazioni dipende da come si intende creare il connettore.

Per informazioni su come impostare le autorizzazioni, fare riferimento a quanto segue:

* Modalità standard
+
** link:concept-install-options-aws.html["Opzioni di installazione del connettore in AWS"]
** link:concept-install-options-azure.html["Opzioni di installazione del connettore in Azure"]
** link:concept-install-options-google.html["Opzioni di installazione del connettore in Google Cloud"]
** link:task-install-connector-on-prem.html#step-4-set-up-cloud-permissions["Impostare le autorizzazioni cloud per le implementazioni on-premise"]


* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions["Impostare le autorizzazioni per la modalità limitata"]
* link:task-prepare-private-mode.html#step-6-prepare-cloud-permissions["Impostare le autorizzazioni per la modalità privata"]


Per visualizzare le autorizzazioni esatte necessarie al connettore per le operazioni quotidiane, fare riferimento alle pagine seguenti:

* link:reference-permissions-aws.html["Scopri come il connettore utilizza le autorizzazioni AWS"]
* link:reference-permissions-azure.html["Scopri come il connettore utilizza le autorizzazioni Azure"]
* link:reference-permissions-gcp.html["Scopri come Connector utilizza le autorizzazioni Google Cloud"]


È responsabilità dell'utente aggiornare i criteri del connettore man mano che vengono aggiunte nuove autorizzazioni nelle versioni successive. Se sono necessarie nuove autorizzazioni, queste verranno elencate nelle note sulla versione.



== Aggiornamenti del connettore

Di solito aggiorniamo il software del connettore ogni mese per introdurre nuove funzionalità e migliorare la stabilità. Mentre la maggior parte dei servizi e delle funzionalità della piattaforma BlueXP  sono offerti tramite software basato su SaaS, alcune funzionalità dipendono dalla versione del connettore. Che include la gestione Cloud Volumes ONTAP, la gestione del cluster ONTAP on-premise, le impostazioni e la guida.

Quando si utilizza BlueXP in modalità standard o limitata, il connettore aggiorna automaticamente il proprio software all'ultima versione, a condizione che disponga di accesso a Internet outbound per ottenere l'aggiornamento software. Se si utilizza BlueXP in modalità privata, è necessario aggiornare manualmente il connettore.

link:task-upgrade-connector.html["Informazioni su come aggiornare manualmente il software del connettore quando si utilizza la modalità privata"].



== Manutenzione del sistema operativo e delle macchine virtuali

La manutenzione del sistema operativo sull'host del connettore è responsabilità dell'utente. Ad esempio, è necessario applicare gli aggiornamenti per la protezione al sistema operativo sull'host del connettore seguendo le procedure standard dell'azienda per la distribuzione del sistema operativo.

Tenere presente che non è necessario interrompere alcun servizio sull'host del connettore quando si applicano aggiornamenti di protezione minori.

Se è necessario arrestare e avviare la macchina virtuale del connettore, è necessario farlo dalla console del provider di cloud o utilizzando le procedure standard per la gestione on-premise.

<<I connettori devono essere sempre operativi,Tenere presente che il connettore deve essere sempre operativo>>.



== Più ambienti di lavoro e connettori

Un connettore può gestire più ambienti di lavoro in BlueXP. Il numero massimo di ambienti di lavoro che un singolo connettore deve gestire varia. Dipende dal tipo di ambiente di lavoro, dal numero di volumi, dalla quantità di capacità gestita e dal numero di utenti.

Se disponi di un'implementazione su larga scala, collabora con il tuo rappresentante NetApp per dimensionare il tuo ambiente. In caso di problemi durante il percorso, contattaci utilizzando la chat integrata nel prodotto.

In alcuni casi, potrebbe essere necessario un solo connettore, ma potrebbero essere necessari due o più connettori.

Ecco alcuni esempi:

* Si dispone di un ambiente multi-cloud (ad esempio, AWS e Azure) e si preferisce avere un connettore in AWS e un altro in Azure. Ciascuno di essi gestisce i sistemi Cloud Volumes ONTAP in esecuzione in tali ambienti.
* Un service provider potrebbe utilizzare un'organizzazione BlueXP  per fornire servizi ai propri clienti, utilizzando al tempo stesso un'altra organizzazione per fornire il disaster recovery a una delle proprie business unit. Ogni organizzazione avrebbe connettori separati.

