---
sidebar: sidebar 
permalink: concept-data-services.html 
keywords: 'concept, connectors, learn about connectors, what are connectors, what is a connector, what"s a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery' 
summary: 'Un connettore è il software NetApp in esecuzione nella rete cloud o on-premise. Esegue le azioni che BlueXP deve eseguire per gestire l"infrastruttura dati. Il connettore esegue costantemente il polling del livello BlueXP SaaS per individuare eventuali azioni da intraprendere. Non è necessario un connettore per iniziare a utilizzare BlueXP, ma è necessario creare un connettore per sbloccare tutte le funzionalità e i servizi di BlueXP.' 
---
= Scopri i servizi BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp BlueXP offre alla tua organizzazione un singolo piano di controllo che ti aiuta a creare, proteggere e gestire i dati nei tuoi ambienti on-premise e cloud.

Puoi scegliere se utilizzare il servizio SaaS BlueXP  (modalità standard), eseguire BlueXP  nel tuo ambiente cloud con restrizioni (modalità limitata) o installarlo all'interno del tuo data center on-premise (modalità privata). Qualunque sia il tuo ambiente, puoi sfruttare la gestione centralizzata e i servizi dati aggiuntivi che mantengono le risorse di storage sane e protette.

La modalità scelta determina i servizi disponibili e le risorse di storage che è possibile gestire.

Prima di iniziare, confronta le diverse risorse di storage supportate da ciascuna modalità e i servizi dati disponibili per scegliere la soluzione più adatta alle esigenze della tua azienda.



== Servizi dati

La tabella seguente indica quali servizi dati sono disponibili in ciascuna modalità di distribuzione, se è necessaria una sottoscrizione e quando è necessario un account di assistenza.

[NOTE]
====
*Connettori* la colonna connettore nella tabella indica quando è necessario disporre di un connettore per la modalità standard. Se si utilizza BlueXP  in modalità limitata o privata, è sempre necessario disporre di un connettore.

====
[cols="24,19,19,19,19"]
|===
|  | Richiede un account di supporto | Richiede il connettore | Richiede l'abbonamento | Disponibilità della modalità 


| Avvisi | Sì | Sì | No | Tutto 


| Backup e recovery | Sì | Sì | Sì | Standard, limitato 


| Classificazione | Sì | No | No | Tutto 


| Copia e sincronizzazione | No | No | Sì |  


| Consulente digitale | Sì | No | No | Tutto 


| Portafoglio digitale | Sì | No* | No | Tutto 


| Disaster recovery | No | Sì | Sì | Standard, limitato 


| Efficienza economica | Sì | Sì | No |  


| Resilienza operativa | Sì | Sì* | No |  


| Protezione ransomware | No | Sì | No | Standard 


| Replica | No | No* | No | Standard, limitato 


| Aggiornamenti software | Sì | No | No | Tutto 


| Gestione dei casi di supporto | Sì | No | No | Tutto 


| Tiering | No | No* | Sì | Standard 


| Caching dei volumi | No | No | No | Standard 
|===


== Storage NetApp

Potrai gestire la maggior parte delle risorse storage di NetApp direttamente da BlueXP , consentendoti di visualizzare tutte le risorse dalla stessa applicazione.

Nella tabella seguente sono elencate le risorse di storage che è possibile gestire da ciascuna modalità di distribuzione, nonché se è necessario un connettore o un abbonamento.

[NOTE]
====
*Connettori* la colonna connettore nella tabella indica quando è necessario disporre di un connettore per la modalità standard. Se si utilizza BlueXP  in modalità limitata o privata, è sempre necessario disporre di un connettore.

====
[cols="24,19,19,19,19"]
|===
|  | Richiede un account di supporto | Richiede il connettore | Richiede l'abbonamento | Disponibilità della modalità 


| Amazon FSX per NetApp ONTAP | Sì | No^1^ | Sì | Standard 


| Storage Amazon S3 | Sì | No | Sì | Standard 


| Storage Azure Blob | Sì | No | No | Standard 


| Azure NetApp Files | No | No^2^ | Sì | Standard, limitato 


| Cloud Volumes ONTAP | Sì | Sì | Sì | Standard, limitato 


| Cloud Volumes Service per Google Cloud | No | No | Sì? | Standard 


| Sistemi e-Series | No | Sì | No | Standard 


| Storage Google Cloud | No | Sì | Sì? | Standard 


| Cluster ONTAP on-premise | Sì | No^3^ | No | Tutto 


| StorageGRID | Sì | Sì | No | Standard, limitato 
|===
^1^ alcune azioni richiedono un collegamento di fabbrica con un connettore o un carico di lavoro BlueXP . https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/concept-fsx-aws.html["Scopri quali azioni richiedono un connettore o un collegamento"^]

^2^ sebbene non sia necessario un connettore per impostare e gestire Azure NetApp Files, è necessario un connettore se si desidera utilizzare la classificazione BlueXP  per eseguire la scansione dei dati Azure NetApp Files.

^3^ sebbene non sia necessario un connettore per il rilevamento diretto di un cluster ONTAP in sede, è necessario un connettore per sfruttare le funzionalità aggiuntive di BlueXP . https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html["Scopri di più sulle opzioni di rilevamento e gestione dei cluster ONTAP on-premise"^]
