---
sidebar: sidebar 
permalink: concept-install-options-google.html 
keywords: install connector google cloud, google cloud install connector, connector google cloud, google cloud connector, install connector gcp, gcp install connector, connector gcp, gcp connector, installation options, manual install 
summary: 'Esistono diversi modi per creare un connettore in Google Cloud. Direttamente da BlueXP è il modo più comune. L"opzione di installazione scelta determina il modo in cui si prepara per l"implementazione.' 
---
= Opzioni di installazione del connettore in Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Esistono diversi modi per creare un connettore in Google Cloud. Direttamente da BlueXP è il modo più comune. L'opzione di installazione scelta determina il modo in cui si prepara per l'implementazione.

Sono disponibili le seguenti opzioni di installazione:

* Creare il connettore direttamente da BlueXP (opzione standard)
+
Questa azione avvia un'istanza della macchina virtuale che esegue Linux e il software del connettore in un VPC a scelta.

* Creare il connettore utilizzando gcloud
+
Questa azione avvia anche un'istanza di macchina virtuale che esegue Linux e il software Connector.

* Scaricare e installare manualmente il software sul proprio host Linux


L'opzione di installazione scelta influisce sul modo in cui si prepara l'installazione. Ciò include il modo in cui si forniscono a BlueXP le autorizzazioni necessarie per autenticare e gestire le risorse in Google Cloud.

link:task-install-connector-google.html["Scopri come installare il connettore in Google Cloud"].
