---
settings:
  name: BlueXP setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentazione di installazione e amministrazione di BlueXP 
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità
      url: "/whats-new.html"
    - title: Limitazioni note
      url: "/reference-limitations.html"
    - title: Modifiche ai sistemi operativi Linux supportati
      url: "/reference-connector-operating-system-changes.html"
  - title: Inizia subito
    entries:
    - title: Scopri le nozioni di base
      entries:
      - title: BlueXP
        url: "/concept-overview.html"
      - title: Connettori
        url: "/concept-connectors.html"
      - title: Modalità di implementazione
        url: "/concept-modes.html"
    - title: Inizia con la modalità standard
      entries:
      - title: Per iniziare il flusso di lavoro
        url: "/task-quick-start-standard-mode.html"
      - title: Preparare il collegamento in rete per la console BlueXP 
        url: "/reference-networking-saas-console.html"
      - title: Iscriviti a BlueXP
        url: "/task-sign-up-saas.html"
      - title: Creare un connettore
        entries:
        - title: AWS
          entries:
          - title: Opzioni di installazione del connettore
            url: "/concept-install-options-aws.html"
          - title: Creare un connettore da BlueXP
            url: "/task-install-connector-aws-bluexp.html"
          - title: Creare un connettore dal mercato
            url: "/task-install-connector-aws-marketplace.html"
          - title: Installare manualmente il connettore
            url: "/task-install-connector-aws-manual.html"
        - title: Azure
          entries:
          - title: Opzioni di installazione del connettore
            url: "/concept-install-options-azure.html"
          - title: Creare un connettore da BlueXP
            url: "/task-install-connector-azure-bluexp.html"
          - title: Creare un connettore dal mercato
            url: "/task-install-connector-azure-marketplace.html"
          - title: Installare manualmente il connettore
            url: "/task-install-connector-azure-manual.html"
        - title: Google Cloud
          entries:
          - title: Opzioni di installazione del connettore
            url: "/concept-install-options-google.html"
          - title: Crea un connettore da BlueXP o gcloud
            url: "/task-install-connector-google-bluexp-gcloud.html"
          - title: Installare manualmente il connettore
            url: "/task-install-connector-google-manual.html"
        - title: On-premise
          url: "/task-install-connector-on-prem.html"
      - title: Iscriviti a BlueXP
        url: "/task-subscribe-standard-mode.html"
      - title: Cosa fare in seguito
        url: "/reference-whats-next.html"
    - title: Inizia con la modalità limitata
      entries:
      - title: Per iniziare il flusso di lavoro
        url: "/task-quick-start-restricted-mode.html"
      - title: Prepararsi per l'implementazione
        url: "/task-prepare-restricted-mode.html"
      - title: Implementare il connettore
        url: "/task-install-restricted-mode.html"
      - title: Iscriviti a BlueXP
        url: "/task-subscribe-restricted-mode.html"
      - title: Cosa fare in seguito
        url: "/reference-whats-next-restricted-mode.html"
    - title: Inizia con la modalità privata
      entries:
      - title: Per iniziare il flusso di lavoro
        url: "/task-quick-start-private-mode.html"
      - title: Prepararsi per l'implementazione
        url: "/task-prepare-private-mode.html"
      - title: Implementare il connettore
        url: "/task-install-private-mode.html"
      - title: BlueXP
        entries:
        - title: Scopri di più sugli account
          url: "/concept-netapp-accounts.html"
        - title: Gestisci il tuo account BlueXP
          url: "/task-managing-netapp-accounts.html"
      - title: Cosa fare in seguito
        url: "/reference-whats-next-private-mode.html"
    - title: Accedere a BlueXP
      url: "/task-logging-in.html"
  - title: Amministrare BlueXP
    entries:
    - title: Gestione delle identità e degli accessi
      entries:
      - title: Ulteriori informazioni su BlueXP  IAM
        url: "/concept-identity-and-access-management.html"
      - title: Introduzione a BlueXP  IAM
        url: "/task-iam-get-started.html"
      - title: Organizzare le risorse con cartelle e progetti
        url: "/task-iam-manage-folders-projects.html"
      - title: Aggiungere membri e gestire le relative autorizzazioni
        url: "/task-iam-manage-members-permissions.html"
      - title: Gestire la gerarchia delle risorse
        url: "/task-iam-manage-resources.html"
      - title: Associare un connettore ad altre cartelle e progetti
        url: "/task-iam-associate-connectors.html"
      - title: Passa da un'organizzazione all'altra, a un progetto e a un connettore
        url: "/task-iam-switch-organizations-projects.html"
      - title: Rinominare l'organizzazione
        url: "/task-iam-rename-organization.html"
      - title: Monitorare o controllare l'attività IAM
        url: "/task-iam-audit-actions-timeline.html"
      - title: Ruoli IAM predefiniti
        url: "/reference-iam-predefined-roles.html"
    - title: Account BlueXP  (solo modalità privata)
      entries:
      - title: Scopri di più sugli account
        url: "/concept-netapp-accounts.html"
      - title: Gestisci il tuo account BlueXP
        url: "/task-managing-netapp-accounts.html"
    - title: Federazione delle identità
      url: "/concept-federation.html"
    - title: Connettori
      entries:
      - title: Gestire la VM e il sistema operativo
        url: "/task-maintain-connectors.html"
      - title: Installare un certificato firmato dalla CA per l'accesso alla console
          Web
        url: "/task-installing-https-cert.html"
      - title: Configurare un connettore per l'utilizzo di un server proxy
        url: "/task-configuring-proxy.html"
      - title: Richiedere l'uso di IMDSv2 su istanze EC2
        url: "/task-require-imdsv2.html"
      - title: Gestire gli aggiornamenti dei connettori
        url: "/task-upgrade-connector.html"
      - title: Utilizzare più connettori
        url: "/task-manage-multiple-connectors.html"
      - title: Eseguire la ricerca guasti del connettore
        url: "/task-troubleshoot-connector.html"
      - title: Disinstallare e rimuovere il connettore
        url: "/task-uninstall-connector.html"
      - title: Configurazione predefinita
        url: "/reference-connector-default-config.html"
      - title: Applicare le autorizzazioni ONTAP in BlueXP 
        url: "/task-ontap-access-connector.html"
    - title: Credenziali e iscrizioni
      entries:
      - title: AWS
        entries:
        - title: Informazioni su credenziali e autorizzazioni
          url: "/concept-accounts-aws.html"
        - title: Gestire credenziali e sottoscrizioni
          url: "/task-adding-aws-accounts.html"
      - title: Azure
        entries:
        - title: Informazioni su credenziali e autorizzazioni
          url: "/concept-accounts-azure.html"
        - title: Gestire credenziali e sottoscrizioni
          url: "/task-adding-azure-accounts.html"
      - title: Google Cloud
        entries:
        - title: Informazioni su progetti e autorizzazioni
          url: "/concept-accounts-gcp.html"
        - title: Gestire credenziali e sottoscrizioni
          url: "/task-adding-gcp-accounts.html"
      - title: Gestire le credenziali NSS associate a un'organizzazione o un account
          BlueXP 
        url: "/task-adding-nss-accounts.html"
      - title: Gestire le credenziali associate all'accesso a BlueXP
        url: "/task-manage-user-credentials.html"
    - title: Monitorare le operazioni BlueXP 
      url: "/task-monitor-cm-operations.html"
  - title: Riferimento
    entries:
    - title: Permessi
      entries:
      - title: Riepilogo delle autorizzazioni
        url: "/reference-permissions.html"
      - title: Autorizzazioni AWS per il connettore
        url: "/reference-permissions-aws.html"
      - title: Autorizzazioni Azure per il connettore
        url: "/reference-permissions-azure.html"
      - title: Permessi Google Cloud per il connettore
        url: "/reference-permissions-gcp.html"
    - title: Porte
      entries:
      - title: Regole del gruppo di sicurezza del connettore in AWS
        url: "/reference-ports-aws.html"
      - title: Regole del gruppo di sicurezza del connettore in Azure
        url: "/reference-ports-azure.html"
      - title: Regole del firewall connettore in Google Cloud
        url: "/reference-ports-gcp.html"
      - title: Porte per il connettore on-premise
        url: "/reference-ports-on-prem.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/task-support-registration.html"
    - title: Richiedi assistenza
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
