---
settings:
  name: Setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti di installazione e amministrazione
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità
      url: "/whats-new.html"
    - title: Limitazioni note
      url: "/reference-limitations.html"
  - title: Inizia subito
    entries:
    - title: Scopri le nozioni di base
      entries:
      - title: BlueXP
        url: "/concept-overview.html"
      - title: Account
        url: "/concept-netapp-accounts.html"
      - title: Connettori
        url: "/concept-connectors.html"
      - title: Modalità di implementazione
        url: "/concept-modes.html"
    - title: Inizia con la modalità standard
      entries:
      - title: Per iniziare il flusso di lavoro
        url: "/task-quick-start-standard-mode.html"
      - title: Preparazione del networking per l'utilizzo della console BlueXP
        url: "/reference-networking-saas-console.html"
      - title: Iscriviti a BlueXP
        url: "/task-sign-up-saas.html"
      - title: Creare un connettore
        entries:
        - title: AWS
          entries:
          - title: Opzioni di installazione del connettore
            url: "/concept-install-options-aws.html"
          - title: Creare un connettore da BlueXP
            url: "/task-install-connector-aws-bluexp.html"
          - title: Creare un connettore dal mercato
            url: "/task-install-connector-aws-marketplace.html"
          - title: Installare manualmente il connettore
            url: "/task-install-connector-aws-manual.html"
        - title: Azure
          entries:
          - title: Opzioni di installazione del connettore
            url: "/concept-install-options-azure.html"
          - title: Creare un connettore da BlueXP
            url: "/task-install-connector-azure-bluexp.html"
          - title: Creare un connettore dal mercato
            url: "/task-install-connector-azure-marketplace.html"
          - title: Installare manualmente il connettore
            url: "/task-install-connector-azure-manual.html"
        - title: Google Cloud
          entries:
          - title: Opzioni di installazione del connettore
            url: "/concept-install-options-google.html"
          - title: Crea un connettore da BlueXP o gcloud
            url: "/task-install-connector-google-bluexp-gcloud.html"
          - title: Installare manualmente il connettore
            url: "/task-install-connector-google-manual.html"
        - title: On-premise
          url: "/task-install-connector-on-prem.html"
      - title: Iscriviti a BlueXP
        url: "/task-subscribe-standard-mode.html"
      - title: Cosa fare in seguito
        url: "/reference-whats-next.html"
    - title: Inizia con la modalità limitata
      entries:
      - title: Per iniziare il flusso di lavoro
        url: "/task-quick-start-restricted-mode.html"
      - title: Prepararsi per l'implementazione
        url: "/task-prepare-restricted-mode.html"
      - title: Implementare il connettore
        url: "/task-install-restricted-mode.html"
      - title: Iscriviti a BlueXP
        url: "/task-subscribe-restricted-mode.html"
      - title: Cosa fare in seguito
        url: "/reference-whats-next-restricted-mode.html"
    - title: Inizia con la modalità privata
      entries:
      - title: Per iniziare il flusso di lavoro
        url: "/task-quick-start-private-mode.html"
      - title: Prepararsi per l'implementazione
        url: "/task-prepare-private-mode.html"
      - title: Implementare il connettore
        url: "/task-install-private-mode.html"
      - title: Cosa fare in seguito
        url: "/reference-whats-next-private-mode.html"
    - title: Accedere a BlueXP
      url: "/task-logging-in.html"
  - title: Amministrare BlueXP
    entries:
    - title: Federazione delle identità
      url: "/concept-federation.html"
    - title: BlueXP
      entries:
      - title: Gestisci il tuo account BlueXP
        url: "/task-managing-netapp-accounts.html"
      - title: Monitorare le operazioni nell'account
        url: "/task-monitor-cm-operations.html"
      - title: Creare un altro account BlueXP
        url: "/task-create-account.html"
      - title: Ruoli utente
        url: "/reference-user-roles.html"
    - title: Connettori
      entries:
      - title: Individuare l'ID di sistema di un connettore
        url: "/task-finding-system-id.html"
      - title: Gestire i connettori esistenti
        url: "/task-managing-connectors.html"
      - title: Installare un certificato HTTPS per un accesso sicuro
        url: "/task-installing-https-cert.html"
      - title: Configurare un connettore per l'utilizzo di un server proxy
        url: "/task-configuring-proxy.html"
      - title: Configurazione predefinita per il connettore
        url: "/reference-connector-default-config.html"
    - title: Credenziali e iscrizioni
      entries:
      - title: AWS
        entries:
        - title: Informazioni su credenziali e autorizzazioni
          url: "/concept-accounts-aws.html"
        - title: Gestire credenziali e sottoscrizioni
          url: "/task-adding-aws-accounts.html"
      - title: Azure
        entries:
        - title: Informazioni su credenziali e autorizzazioni
          url: "/concept-accounts-azure.html"
        - title: Gestire credenziali e sottoscrizioni
          url: "/task-adding-azure-accounts.html"
      - title: Google Cloud
        entries:
        - title: Informazioni su progetti e autorizzazioni
          url: "/concept-accounts-gcp.html"
        - title: Gestire credenziali e sottoscrizioni
          url: "/task-adding-gcp-accounts.html"
      - title: Gestire le credenziali NSS associate a un account BlueXP
        url: "/task-adding-nss-accounts.html"
      - title: Gestire le credenziali associate all'accesso a BlueXP
        url: "/task-manage-user-credentials.html"
  - title: Riferimento
    entries:
    - title: Permessi
      entries:
      - title: Riepilogo delle autorizzazioni
        url: "/reference-permissions.html"
      - title: Autorizzazioni AWS per il connettore
        url: "/reference-permissions-aws.html"
      - title: Autorizzazioni Azure per il connettore
        url: "/reference-permissions-azure.html"
      - title: Permessi Google Cloud per il connettore
        url: "/reference-permissions-gcp.html"
    - title: Porte
      entries:
      - title: Regole del gruppo di sicurezza del connettore in AWS
        url: "/reference-ports-aws.html"
      - title: Regole del gruppo di sicurezza del connettore in Azure
        url: "/reference-ports-azure.html"
      - title: Regole del firewall connettore in Google Cloud
        url: "/reference-ports-gcp.html"
      - title: Porte per il connettore on-premise
        url: "/reference-ports-on-prem.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/task-support-registration.html"
    - title: Richiedi assistenza
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Inizia subito
    links:
    - title: Scopri BlueXP
      url: concept-overview.html
    - title: Scopri le modalità di implementazione
      url: concept-modes.html
    - title: Inizia con la modalità standard
      url: "/task-quick-start-standard-mode.html"
    - title: Inizia con la modalità limitata
      url: "/task-quick-start-restricted-mode.html"
    - title: Inizia con la modalità privata
      url: "/task-quick-start-private-mode.html"
  - title: BlueXP
    links:
    - title: Scopri di più sugli account BlueXP
      url: concept-netapp-accounts.html
    - title: Gestisci il tuo account BlueXP
      url: task-managing-netapp-accounts.html
    - title: Monitorare le operazioni nell'account
      url: task-monitor-cm-operations.html
  - title: Connettori
    links:
    - title: Scopri di più sui connettori
      url: concept-connectors.html
    - title: Gestire i connettori
      url: task-managing-connectors.html
    - title: Visualizza le autorizzazioni AWS
      url: reference-permissions-aws.html
    - title: Visualizzare le autorizzazioni di Azure
      url: reference-permissions-azure.html
    - title: Visualizzare le autorizzazioni di Google Cloud
      url: reference-permissions-gcp.html
  - title: AWS
    links:
    - title: Inizia subito in una regione AWS standard
      url: task-quick-start-standard-mode.html
    - title: Inizia subito in un'area di AWS GovCloud
      url: task-quick-start-restricted-mode.html
    - title: Inizia in AWS Secret o Top Secret Cloud
      url: https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-getting-started-aws-c2s.html
    - title: Visualizzare i criteri IAM per il connettore
      url: reference-permissions-aws.html
    - title: Gestire credenziali e sottoscrizioni
      url: task-adding-aws-accounts.html
  - title: Azure
    links:
    - title: Inizia in una regione Azure standard
      url: task-quick-start-standard-mode.html
    - title: Inizia subito in un'area Azure Government
      url: task-quick-start-restricted-mode.html
    - title: Inizia subito con Azure IL6
      url: task-quick-start-private-mode.html
    - title: Visualizzare il ruolo personalizzato per il connettore
      url: reference-permissions-azure.html
    - title: Gestire credenziali e sottoscrizioni
      url: task-adding-azure-accounts.html
  - title: Google Cloud
    links:
    - title: Inizia subito in un'area standard di Google Cloud
      url: task-quick-start-standard-mode.html
    - title: Visualizzare l'account del servizio per il connettore
      url: reference-permissions-gcp.html
    - title: Gestire credenziali e sottoscrizioni
      url: task-adding-gcp-accounts.html
  - title: On-premise
    links:
    - title: Installare e configurare un connettore in modalità standard
      url: task-install-connector-on-prem.html
    - title: Installare e configurare un connettore in modalità privata
      url: task-quick-start-private-mode.html
  - title: Accesso in corso
    links:
    - title: Accedere a BlueXP
      url: task-logging-in.html
    - title: Utilizzo della federazione delle identità con BlueXP
      url: concept-federation.html
  - title: Blog e community
    links:
    - title: Community NetApp
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Blog BlueXP
      url: https://bluexp.netapp.com/blog
    - title: Webinar sul cloud
      url: https://bluexp.netapp.com/events
product-family:
  name: BlueXP
  repo: bluexp-family
