---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: Quando utilizzi la console basata sul web BlueXP fornita attraverso il livello SaaS, contatta diversi endpoint quando completi alcuni task amministrativi. I computer che accedono alla console BlueXP devono disporre di connessioni a questi endpoint. 
---
= Preparare il collegamento in rete per la console BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando utilizzi la console basata sul web BlueXP fornita attraverso il livello SaaS, contatta diversi endpoint quando completi alcuni task amministrativi. I computer che accedono alla console BlueXP devono disporre di connessioni a questi endpoint.

Questi endpoint vengono contattati dal computer di un utente quando si completano azioni specifiche dalla console BlueXP. Fai anche riferimento ai requisiti di rete per il connettore e per servizi BlueXP specifici. Per ulteriori informazioni, fare riferimento ai link correlati alla fine di questa pagina.

[cols="2*"]
|===
| Endpoint | Scopo 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | Il browser Web contatta questi URL quando si utilizza la console basata su Web BlueXP. 


| \https://aiq.netapp.com | Richieste per accedere al Digital Advisor di BlueXP. 


 a| 
Servizi AWS (amazonaws.com):

* CloudFormation
* Elastic Compute Cloud (EC2)
* Servizio di gestione delle chiavi (KMS)
* Servizio token di sicurezza (STS)
* S3 (Simple Storage Service)

| Necessario per implementare un connettore da BlueXP in AWS. L'endpoint esatto dipende dalla regione in cui viene implementato il connettore. https://docs.aws.amazon.com/general/latest/gr/rande.html["Per ulteriori informazioni, fare riferimento alla documentazione AWS."^] 


| \https://management.azure.com

\https://login.microsoftonline.com | Necessario per implementare un connettore da BlueXP nella maggior parte delle regioni Azure. 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | Necessario per implementare un connettore da BlueXP nelle regioni di Azure Germania. 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | Necessario per implementare un connettore da BlueXP nelle regioni Azure US Gov. 


| \https://www.googleapis.com | Necessario per implementare un connettore di BlueXP in Google Cloud. 


| \https://signin.b2c.netapp.com | Necessario per aggiornare le credenziali NetApp Support Site (NSS) o per aggiungere nuove credenziali NSS a BlueXP. 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | Il browser Web si connette a questi endpoint per un'autenticazione utente centralizzata tramite BlueXP. 


| \https://widget.intercom.io | Per chat in-product che ti consente di parlare con gli esperti cloud di NetApp. 
|===
Oltre a questi endpoint, è anche necessario garantire che il connettore disponga dell'accesso a Internet in uscita per contattare endpoint specifici per le operazioni quotidiane. Puoi trovare l'elenco di questi endpoint seguendo i link nella sezione successiva.

.Informazioni correlate
* Preparare il collegamento in rete per il connettore
+
** link:task-install-connector-aws-bluexp.html#step-1-set-up-networking["Configurare la rete AWS"]
** link:task-install-connector-azure-bluexp.html#step-1-set-up-networking["Configurare il networking Azure"]
** link:task-install-connector-google-bluexp-gcloud.html#step-1-set-up-networking["Configurare il networking Google Cloud"]
** link:task-install-connector-on-prem.html#step-3-set-up-networking["Configurare il networking on-premise"]


* Preparare il networking per i servizi BlueXP
+
Fai riferimento alla documentazione di ogni servizio BlueXP.

+
https://docs.netapp.com/us-en/bluexp-family/["Documentazione BlueXP"^]


