---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: Quando utilizzi la console basata sul web BlueXP fornita attraverso il livello SaaS, contatta diversi endpoint quando completi alcuni task amministrativi. I computer che accedono alla console BlueXP devono disporre di connessioni a questi endpoint. 
---
= Preparare il collegamento in rete per la console BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando si accede e si utilizza la console web, BlueXP contatta diversi endpoint per completare le azioni avviate. I computer che accedono alla console devono disporre di connessioni a questi endpoint.

Questi endpoint vengono contattati in due scenari:

* Dal computer di un utente quando completa le azioni dal  https://console.bluexp.netapp.com["Console BlueXP basata su web"^] disponibile come software come servizio (SaaS).
* Dal computer di un utente quando si apre un browser Web, immettere l'indirizzo IP dell'host del connettore, quindi accedere e configurare il connettore. Questi passi sono necessari se si installa manualmente il connettore.


[cols="2*"]
|===
| Endpoint | Scopo 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | Questo è l'endpoint che devi immettere nel tuo browser web per utilizzare la console basata sul web. 


| \https://api.bluexp.netapp.com | La console basata sul Web contatta questo endpoint per interagire con l'API per azioni correlate ad autorizzazioni, licenze, abbonamenti, credenziali, notifiche e altro ancora. 


| \https://aiq.netapp.com | Necessario per accedere al consulente digitale. 


 a| 
Servizi AWS (amazonaws.com):

* CloudFormation
* Elastic Compute Cloud (EC2)
* Servizio di gestione delle chiavi (KMS)
* Servizio token di sicurezza (STS)
* S3 (Simple Storage Service)

| Necessario per implementare un connettore da BlueXP in AWS. L'endpoint esatto dipende dalla regione in cui si distribuisce il connettore.  https://docs.aws.amazon.com/general/latest/gr/rande.html["Per maggiori dettagli, consultare la documentazione AWS."] Suggerimento:  https://docs.aws.amazon.com/general/latest/gr/rande.html["Per maggiori dettagli, consultare la documentazione AWS."] 


| \https://management.azure.com

\https://login.microsoftonline.com | Necessario per implementare un connettore da BlueXP nella maggior parte delle regioni Azure. 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | Necessario per implementare un connettore da BlueXP nelle regioni di Azure Germania. 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | Necessario per implementare un connettore da BlueXP nelle regioni Azure US Gov. 


| \https://www.googleapis.com | Necessario per implementare un connettore di BlueXP in Google Cloud. 


| \https://signin.b2c.netapp.com | Necessario per aggiornare le credenziali NetApp Support Site (NSS) o per aggiungere nuove credenziali NSS a BlueXP. 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | Il browser Web si connette a questi endpoint per un'autenticazione utente centralizzata tramite BlueXP. 


| \https://widget.intercom.io | Per la chat all'interno del prodotto che ti consente di parlare con l'assistenza NetApp. 
|===
Assicurarsi che il connettore disponga di accesso a Internet in uscita per contattare gli endpoint per le operazioni quotidiane. Seguire i link nella sezione successiva per trovare l'elenco di questi endpoint.

.Informazioni correlate
* Preparare il collegamento in rete per il connettore
+
** link:task-install-connector-aws-bluexp.html#step-1-set-up-networking["Configurare la rete AWS"]
** link:task-install-connector-azure-bluexp.html#step-1-set-up-networking["Configurare il networking Azure"]
** link:task-install-connector-google-bluexp-gcloud.html#step-1-set-up-networking["Configurare il networking Google Cloud"]
** link:task-install-connector-on-prem.html#step-3-set-up-networking["Configurare la rete locale"]


* Preparare il networking per i servizi BlueXP
+
Fai riferimento alla documentazione di ogni servizio BlueXP.

+
https://docs.netapp.com/us-en/bluexp-family/["Documentazione BlueXP"^]


