---
sidebar: sidebar 
permalink: reference-host-requirements-google.html 
keywords: cpu requirements, ram requirements, google cloud requirements, google cloud host requirements, connector host requirements, gcp machine type, machine type 
summary: 'Il software del connettore deve essere eseguito su un host che soddisfi i requisiti specifici del sistema operativo, della RAM, dei requisiti delle porte e così via. Se si prevede di installare manualmente il connettore, assicurarsi che l"host soddisfi questi requisiti. Assicurarsi che l"host soddisfi questi requisiti prima di installare il connettore.' 
---
= Esaminare i requisiti degli host dei connettori per le installazioni di Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il software del connettore deve essere eseguito su un host che soddisfi i requisiti specifici del sistema operativo, della RAM, dei requisiti delle porte e così via. Se si prevede di installare manualmente il connettore, assicurarsi che l'host soddisfi questi requisiti.

Quando si implementa il connettore da BlueXP o utilizzando glcoud, l'immagine include il sistema operativo e i componenti software richiesti.

Host dedicato:: Il connettore non è supportato su un host condiviso con altre applicazioni. L'host deve essere un host dedicato.
Sistemi operativi supportati::
+
--
* Ubuntu 22.04
* CentOS 7.6, 7.7, 7.8 e 7.9
* Red Hat Enterprise Linux 7.6, 7.7, 7.8 e 7.9
+
L'host deve essere registrato con Red Hat Subscription Management. Se non è registrato, l'host non può accedere ai repository per aggiornare il software di terze parti richiesto durante l'installazione del connettore.

+
Il connettore è supportato dalle versioni in lingua inglese di questi sistemi operativi.



--
Hypervisor:: È richiesto un hypervisor bare metal o in hosting certificato per l'esecuzione di Ubuntu, CentOS o Red Hat Enterprise Linux.
+
--
https://access.redhat.com/certified-hypervisors["Soluzione Red Hat: Quali hypervisor sono certificati per eseguire Red Hat Enterprise Linux?"^]

--
CPU:: 4 core o 4 vCPU
RAM:: 14 GB
Tipo di macchina Google Cloud:: Un tipo di istanza che soddisfa i requisiti di CPU e RAM indicati in precedenza. Consigliamo n2-standard-4.
+
--
Il connettore è supportato in Google Cloud su un'istanza di macchina virtuale con un sistema operativo che supporta https://cloud.google.com/compute/shielded-vm/docs/shielded-vm["Funzioni di VM schermate"^]

--
Spazio su disco in /opz:: 100 GiB di spazio deve essere disponibile
Spazio su disco in /var:: 20 GiB di spazio deve essere disponibile
Motore Docker:: Prima di installare il connettore, è necessario installare Docker Engine versione 19.3.1 o successiva sull'host. https://docs.docker.com/engine/install/["Visualizzare le istruzioni di installazione"^]

