---
sidebar: sidebar 
permalink: reference-iam-platform-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: 'La gestione delle identità e degli accessi di BlueXP  include diversi ruoli predefiniti che è possibile assegnare ai membri dell"organizzazione.' 
---
= Ruoli di accesso alla piattaforma BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
I ruoli della piattaforma sono i ruoli più ampi che puoi assegnare agli utenti e consentire tutte le autorizzazioni per l'amministrazione BlueXP, inclusa l'assegnazione di ruoli e l'aggiunta di utenti. Gli utenti con ruoli della piattaforma hanno accesso a tutti i servizi dati e le applicazioni all'interno di BlueXP . BlueXP  include due ruoli di piattaforma: *Amministratore organizzazione* e *Amministratore cartella o Amministratore progetto*. La differenza principale tra i due ruoli della piattaforma BlueXP  è l'ambito in cui si applica il ruolo.

.Esempio di ruoli organizzativi in BlueXP  per una grande organizzazione multinazionale
XYZ Corporation, una multinazionale, intende separare l'accesso alle risorse di storage dei dati in base alle aree geografiche: Nord America, Europa e Asia-Pacifico. Vogliono che ogni regione abbia il controllo esclusivo sulle proprie risorse, pur mantenendo una supervisione centralizzata.

A tal fine, una persona a cui è stato assegnato il ruolo di amministratore dell'organizzazione in BlueXP  di XYZ Corporation crea un ambiente di lavoro iniziale e quindi crea cartelle separate in BlueXP  per ciascuna regione. La cartella di ogni regione contiene progetti (con risorse associate) correlati a tale regione. L'amministratore *organizzazione* assegna a un utente BlueXP  in ciascuna regione il ruolo *cartella o amministratore progetto*.

Una volta completata la configurazione iniziale, gli amministratori regionali con il ruolo *cartella o project admin* possono creare nuovi ambienti di lavoro e aggiungere utenti all'interno delle rispettive aree geografiche. Questi amministratori regionali possono anche aggiungere/rimuovere/rinominare cartelle e progetti a cui sono assegnati. L'amministratore dell'organizzazione* eredita le autorizzazioni per qualsiasi nuovo ambiente di lavoro o risorsa, mantenendo la visibilità dell'utilizzo dello storage nell'intera organizzazione.

La tabella seguente indica le azioni che ogni ruolo della piattaforma BlueXP  può eseguire.

[cols="2,1,1"]
|===
| Attività | Amministratore dell'organizzazione | Amministratore cartella o progetto 


| Creare connettori | Sì | No 


| Creare, modificare o eliminare ambienti di lavoro (aggiungere o rilevare nuove risorse utilizzando BlueXP  Canvas) | Sì | Sì 


| Creare cartelle e progetti, compresa l'eliminazione | Sì | No 


| Rinominare le cartelle e i progetti esistenti | Sì | Sì 


| Assegnare ruoli e aggiungere utenti | Sì | Sì 


| Associare le risorse alle cartelle e ai progetti | Sì | Sì 


| Associa i connettori a cartelle e progetti | Sì | No 


| Rimuovere i connettori da cartelle e progetti | Sì | No 


| Gestisci connettori (modifica certificati, impostazioni e così via) | Sì | No 


| Gestire le credenziali da Impostazioni > credenziali | Sì | Sì 


| Visualizza la timeline di BlueXP  | Sì | Sì 


| Utilizza i servizi BlueXP  | Sì | Sì 


| Registrati BlueXP  per supportare e inviare i casi | Sì | Sì 
|===