---
sidebar: sidebar 
permalink: reference-user-roles.html 
keywords: user, users, roles, role, task, permission, permissions, tasks, admin, Account Admin, Workspace Admin, Cloud Compliance Viewer, Cloud Data Sense, SnapCenter Admin 
summary: 'I ruoli Amministratore account, Amministratore area di lavoro, Visualizzatore conformità e Amministratore SnapCenter forniscono autorizzazioni specifiche agli utenti. È possibile assegnare uno di questi ruoli quando si associa un nuovo utente all"account BlueXP.' 
---
= Ruoli utente
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando utilizzi BlueXP  in modalità limitata o privata, utilizzerai un account _BlueXP _ per gestire gli utenti. È possibile fornire autorizzazioni specifiche agli utenti dell'account selezionando uno dei seguenti ruoli: Account Admin, Workspace Admin, Compliance Viewer e SnapCenter Admin.

Se utilizzi BlueXP  in modalità standard, non avrai un account BlueXP . Avrete invece un'organizzazione _BlueXP _ gestita utilizzando la gestione delle identità e degli accessi (IAM) di BlueXP .

* link:concept-identity-and-access-management.html["Ulteriori informazioni su BlueXP  IAM"]
* link:concept-modes.html["Scopri le modalità di implementazione di BlueXP"]


[cols="24,19,19,19,19"]
|===
| Attività | Amministratore account | Amministratore dello spazio di lavoro | Compliance Viewer | Amministratore SnapCenter 


| Creare connettori | Sì | No | No | No 


| Gestire gli ambienti di lavoro | Sì | Sì | No | Sì 


| Abilitare i servizi negli ambienti di lavoro | Sì | Sì | No | Sì 


| Utilizza i servizi BlueXP  | Sì | Sì | No | Sì 


| Rimuovere gli ambienti di lavoro da un'area di lavoro | Sì | Sì | No | No 


| Eliminare gli ambienti di lavoro | Sì | Sì | No | No 


| Visualizzare lo stato della replica dei dati | Sì | Sì | No | No 


| Visualizza la timeline | Sì | Sì | No | No 


| Passare da un'area di lavoro all'altra | Sì | Sì | Sì | Sì 


| Visualizzare i risultati della scansione di classificazione BlueXP | Sì | Sì | Sì | No 


| Ricevere il report Cloud Volumes ONTAP | Sì | No | No | No 


| Gestire gli account BlueXP | Sì | No | No | No 


| Gestire le credenziali | Sì | Sì | No | No 


| Modificare le impostazioni di BlueXP | Sì | Sì | No | No 


| Visualizza e gestisci la dashboard di supporto | Sì | Sì | No | No 
|===
.Link correlato
link:task-managing-netapp-accounts.html["Gestisci il tuo account BlueXP"]
