---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking 
summary: 'Quando si inizia a utilizzare BlueXP, assicurarsi che la rete consenta l"accesso a endpoint specifici dalla console BlueXP. A seconda del modo in cui si intende utilizzare BlueXP, potrebbe essere necessario configurare la rete per un connettore e per servizi BlueXP specifici.' 
---
= Preparare la rete
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando si inizia a utilizzare BlueXP, assicurarsi che la rete consenta l'accesso a endpoint specifici dalla console BlueXP. A seconda del modo in cui si intende utilizzare BlueXP, potrebbe essere necessario configurare la rete per un connettore e per servizi BlueXP specifici.



== Preparare la rete per l'accesso dell'utente alla console BlueXP

Quando utilizzi la console basata sul web BlueXP fornita attraverso il layer SaaS, contatta diversi endpoint per completare le attività di gestione dei dati. Il computer che esegue il browser Web deve disporre di connessioni a questi endpoint.

[cols="2*"]
|===
| Endpoint | Scopo 


| \https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com | Il browser Web contatta questi URL quando si utilizza la console basata su Web BlueXP. 


 a| 
Servizi AWS (amazonaws.com):

* CloudFormation
* Elastic Compute Cloud (EC2)
* Servizio di gestione delle chiavi (KMS)
* Servizio token di sicurezza (STS)
* S3 (Simple Storage Service)

| Necessario per implementare un connettore da BlueXP in AWS. L'endpoint esatto dipende dalla regione in cui viene implementato il connettore. https://docs.aws.amazon.com/general/latest/gr/rande.html["Per ulteriori informazioni, fare riferimento alla documentazione AWS."^] 


| \https://management.azure.com

\https://login.microsoftonline.com | Necessario per implementare un connettore da BlueXP nella maggior parte delle regioni Azure. 


| \https://management.microsoftazure.de

\https://login.microsoftonline.de | Necessario per implementare un connettore da BlueXP nelle regioni di Azure Germania. 


| \https://management.usgovcloudapi.net

\https://login.microsoftonline.com | Necessario per implementare un connettore da BlueXP nelle regioni Azure US Gov. 


| \https://www.googleapis.com | Necessario per implementare un connettore di BlueXP in Google Cloud. 


| \https://signin.b2c.netapp.com | Necessario per aggiornare le credenziali NetApp Support Site (NSS) o per aggiungere nuove credenziali NSS a BlueXP. 


| \https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com | Il browser Web si connette a questi endpoint per un'autenticazione utente centralizzata tramite BlueXP. 


| \https://widget.intercom.io | Per chat in-product che ti consente di parlare con gli esperti cloud di NetApp. 
|===
Oltre a questi endpoint, è anche necessario garantire che il connettore disponga dell'accesso a Internet in uscita per contattare endpoint specifici per le operazioni quotidiane. Puoi trovare l'elenco di questi endpoint seguendo i link nella sezione successiva.



== Preparare il collegamento in rete per un connettore

Il modo in cui prepari la tua rete per un connettore dipende da dove intendi installare il connettore, che può trovarsi nel cloud o in sede. Per ulteriori informazioni sui requisiti di rete dei connettori, fare riferimento alle seguenti pagine:

* link:task-set-up-networking-aws.html["Configurare la rete AWS"]
* link:task-set-up-networking-azure.html["Configurare il networking Azure"]
* link:task-set-up-networking-google.html["Configurare il networking Google Cloud"]
* link:task-set-up-networking-on-prem.html["Configurare il networking on-premise"]




== Preparare il networking per i servizi BlueXP

Quando si inizia a utilizzare BlueXP, è necessario assicurarsi di aver soddisfatto i requisiti di rete per i servizi BlueXP che si intende utilizzare. Per ulteriori informazioni, fare riferimento alla documentazione relativa a ciascun servizio.

https://docs.netapp.com/us-en/bluexp-family/["Documentazione BlueXP"^]
