---
sidebar: sidebar 
permalink: reference-host-requirements-aws.html 
keywords: cpu requirements, ram requirements, aws requirements, aws host requirements, connector host requirements, ec2 instance type 
summary: 'Il software del connettore deve essere eseguito su un host che soddisfi i requisiti specifici del sistema operativo, della RAM, dei requisiti delle porte e così via. Se si prevede di installare manualmente il connettore, assicurarsi che l"host soddisfi questi requisiti.' 
---
= Esaminare i requisiti degli host del connettore per le installazioni AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il software del connettore deve essere eseguito su un host che soddisfi i requisiti specifici del sistema operativo, della RAM, dei requisiti delle porte e così via. Se si prevede di installare manualmente il connettore, assicurarsi che l'host soddisfi questi requisiti.

Quando si implementa il connettore da BlueXP o da AWS Marketplace, l'immagine include il sistema operativo e i componenti software richiesti.

Host dedicato:: Il connettore non è supportato su un host condiviso con altre applicazioni. L'host deve essere un host dedicato.
Sistemi operativi supportati::
+
--
* Ubuntu 22.04
* CentOS 7.6, 7.7, 7.8 e 7.9
* Red Hat Enterprise Linux 7.6, 7.7, 7.8 e 7.9
+
L'host deve essere registrato con Red Hat Subscription Management. Se non è registrato, l'host non può accedere ai repository per aggiornare il software di terze parti richiesto durante l'installazione del connettore.

+
Il connettore è supportato dalle versioni in lingua inglese di questi sistemi operativi.



--
Hypervisor:: È richiesto un hypervisor bare metal o in hosting certificato per l'esecuzione di Ubuntu, CentOS o Red Hat Enterprise Linux.
+
--
https://access.redhat.com/certified-hypervisors["Soluzione Red Hat: Quali hypervisor sono certificati per eseguire Red Hat Enterprise Linux?"^]

--
CPU:: 4 core o 4 vCPU
RAM:: 14 GB
Tipo di istanza AWS EC2:: Un tipo di istanza che soddisfa i requisiti di CPU e RAM indicati in precedenza. Si consiglia di utilizzare t3.xlarge.
Coppia di chiavi:: Quando si crea il connettore da BlueXP o da AWS Marketplace, è necessario selezionare una coppia di chiavi EC2 da utilizzare con l'istanza.
Spazio su disco in /opz:: 100 GiB di spazio deve essere disponibile
Spazio su disco in /var:: 20 GiB di spazio deve essere disponibile
Motore Docker:: Prima di installare il connettore, è necessario installare Docker Engine versione 19.3.1 o successiva sull'host. https://docs.docker.com/engine/install/["Visualizzare le istruzioni di installazione"^]

