---
sidebar: sidebar 
permalink: reference-iam-disaster-rec-roles.html 
keywords: disaster recovery, role-based access control, failover admin, replication plans, job- monitoring, business continuity, compliance- management, operational governance, access delegation, rbac, IAM roles 
summary: La gestione delle identità e degli accessi BlueXP offre diversi ruoli che puoi assegnare ai membri della tua organizzazione che utilizzano il servizio di ripristino di emergenza. 
---
= Ruoli BlueXP disaster recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
È possibile assegnare i seguenti ruoli agli utenti per consentire loro di accedere al servizio di backup e ripristino all'interno BlueXP. I ruoli di backup e ripristino offrono la flessibilità di assegnare agli utenti un ruolo specifico per le attività che devono svolgere all'interno dell'organizzazione. La modalità di assegnazione dei ruoli dipende dalle procedure aziendali e di gestione dello storage.

Il ripristino di emergenza utilizza i seguenti ruoli:

* *Amministratore del ripristino di emergenza*: Esegue qualsiasi azione.
* *Amministratore del failover per il disaster recovery*: esegue il failover e le migrazioni.
* *Amministratore dell'applicazione di disaster recovery*: Creazione di piani di replica. Modifica di piani di replica. Avvio di failover di prova.
* *Visualizzatore di disaster recovery*: visualizza solo informazioni.


La tabella seguente indica le azioni che ciascun ruolo può eseguire.

[cols="30,20a,20a,20a,20a"]
|===
| Funzione e azione | Amministratore del ripristino di emergenza | Amministratore del failover del ripristino di emergenza | Amministratore dell'applicazione di ripristino di emergenza | Visualizzatore di ripristino di emergenza 


| Visualizza dashboard e tutte le schede  a| 
Sì
 a| 
Sì
 a| 
Sì
 a| 
Sì



| Inizia la prova gratuita  a| 
Sì
 a| 
No
 a| 
No
 a| 
No



| Avvia il rilevamento dei carichi di lavoro  a| 
Sì
 a| 
No
 a| 
No
 a| 
No



| Visualizza le informazioni sulla licenza  a| 
Sì
 a| 
Sì
 a| 
Sì
 a| 
Sì



| Attiva la licenza  a| 
Sì
 a| 
No
 a| 
Sì
 a| 
No



5+| *Nella scheda Siti*: 


| Visualizza i siti  a| 
Sì
 a| 
Sì
 a| 
Sì
 a| 
Sì



| Aggiungere, modificare o eliminare siti  a| 
Sì
 a| 
No
 a| 
No
 a| 
No



5+| *Nella scheda Piani di replicazione*: 


| Visualizza i piani di replicazione  a| 
Sì
 a| 
Sì
 a| 
Sì
 a| 
Sì



| Visualizza i dettagli del piano di replicazione  a| 
Sì
 a| 
Sì
 a| 
Sì
 a| 
Sì



| Creare o modificare piani di replicazione  a| 
Sì
 a| 
Sì
 a| 
Sì
 a| 
No



| Creare report  a| 
Sì
 a| 
No
 a| 
No
 a| 
No



| Visualizza istantanee  a| 
Sì
 a| 
Sì
 a| 
Sì
 a| 
Sì



| Eseguire test di failover  a| 
Sì
 a| 
Sì
 a| 
Sì
 a| 
No



| Eseguire failover  a| 
Sì
 a| 
Sì
 a| 
No
 a| 
No



| Eseguire failback  a| 
Sì
 a| 
Sì
 a| 
No
 a| 
No



| Eseguire migrazioni  a| 
Sì
 a| 
Sì
 a| 
No
 a| 
No



5+| *Nella scheda Gruppi di risorse*: 


| Visualizza i gruppi di risorse  a| 
Sì
 a| 
Sì
 a| 
Sì
 a| 
Sì



| Crea, modifica o elimina gruppi di risorse  a| 
Sì
 a| 
No
 a| 
Sì
 a| 
No



5+| *Nella scheda Monitoraggio lavori*: 


| Visualizzare i lavori  a| 
Sì
 a| 
No
 a| 
Sì
 a| 
Sì



| Annulla lavori  a| 
Sì
 a| 
Sì
 a| 
Sì
 a| 
No

|===