---
sidebar: sidebar 
permalink: reference-iam-platform-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: Assegna ruoli di piattaforma agli utenti per concedere autorizzazioni per gestire BlueXP, assegnare ruoli, aggiungere utenti, creare connettori e gestire federazioni. 
---
= Ruoli di accesso alla piattaforma BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Assegna ruoli di piattaforma agli utenti per concedere autorizzazioni per gestire BlueXP, assegnare ruoli, aggiungere utenti, creare connettori e gestire federazioni.

.Esempio di ruoli organizzativi in BlueXP  per una grande organizzazione multinazionale
XYZ Corporation organizza l'accesso all'archiviazione dei dati in base alla regione (Nord America, Europa e Asia-Pacifico), garantendo al contempo il controllo di ogni regione e una supervisione centralizzata.

L'*amministratore dell'organizzazione* in BlueXP di XYZ Corporation crea un'organizzazione iniziale e cartelle separate per ogni regione. La cartella di ogni regione contiene progetti (con risorse associate) correlati a tale regione. L'amministratore *organizzazione* assegna a un utente BlueXP  in ciascuna regione il ruolo *cartella o amministratore progetto*.

Gli amministratori regionali con il ruolo di *Amministratore cartella o progetto* gestiscono le proprie regioni (cartelle) aggiungendo nuove risorse e utenti. Questi amministratori regionali possono anche aggiungere, rimuovere o rinominare le cartelle e i progetti che gestiscono. L'*Amministratore organizzazione* eredita le autorizzazioni per tutte le nuove risorse, mantenendo la visibilità sull'utilizzo dello spazio di archiviazione nell'intera organizzazione.

All'interno della stessa organizzazione, a un utente viene assegnato il ruolo di *Amministratore federazione* per gestire la federazione dell'organizzazione con il proprio IdP aziendale. Questo utente può aggiungere o rimuovere organizzazioni federate, ma non può gestire utenti o risorse all'interno dell'organizzazione. L'organizzazione assegna a un utente il ruolo di *Visualizzatore federazione* per verificare lo stato della federazione e visualizzare le organizzazioni federate senza apportare modifiche.

Le tabelle seguenti indicano le azioni che ogni ruolo della piattaforma BlueXP può eseguire.



== Ruoli di amministrazione dell'organizzazione

[cols="2,1,1"]
|===
| Attività | Amministratore dell'organizzazione | Amministratore cartella o progetto 


| Creare connettori | Sì | No 


| Creare, modificare o eliminare ambienti di lavoro (aggiungere o rilevare nuove risorse utilizzando BlueXP  Canvas) | Sì | Sì 


| Creare cartelle e progetti, compresa l'eliminazione | Sì | No 


| Rinominare le cartelle e i progetti esistenti | Sì | Sì 


| Assegnare ruoli e aggiungere utenti | Sì | Sì 


| Associare le risorse alle cartelle e ai progetti | Sì | Sì 


| Associa i connettori a cartelle e progetti | Sì | No 


| Rimuovere i connettori da cartelle e progetti | Sì | No 


| Gestisci connettori (modifica certificati, impostazioni e così via) | Sì | No 


| Gestire le credenziali da Impostazioni > credenziali | Sì | Sì 


| Crea, gestisci e visualizza le federazioni | Sì | No 


| Registrati per ricevere supporto e inviare casi | Sì | Sì 


| Utilizzare i servizi dati | Sì | Sì 


| Visualizza la cronologia e le notifiche BlueXP | Sì | Sì 
|===


== Ruoli della Federazione

[cols="2,1,1"]
|===
| Attività | Amministratore della federazione | Visualizzatore della federazione 


| Creare una federazione | Sì | No 


| Verificare un dominio | Sì | No 


| Aggiungere un dominio a una federazione | Sì | No 


| Disattivare ed eliminare le federazioni | Sì | No 


| Federazioni di prova | Sì | No 


| Visualizza le federazioni e i loro dettagli | Sì | Sì 
|===