---
sidebar: sidebar 
permalink: reference-iam-keystone-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, identity and access management, access roles, admin 
summary: 'La gestione delle identità e degli accessi di BlueXP  fornisce due ruoli amministrativi che è possibile assegnare ai membri dell"organizzazione.' 
---
= Ruoli di accesso di Keystone per BlueXP 
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
I ruoli Keystone offrono l'accesso alle dashboard Keystone e consentono agli utenti di visualizzare e gestire l'iscrizione Keystone. Esistono due ruoli Keystone: Keystone admin e Keystone Viewer. La differenza principale tra i due ruoli è rappresentata dalle azioni che possono intraprendere in Keystone. Il ruolo di amministratore Keystone è l'unico ruolo autorizzato a creare richieste di servizio o a modificare le iscrizioni.

.Esempio di ruoli Keystone in BlueXP 
XYZ Corporation dispone di quattro tecnici di storage provenienti da reparti diversi che visualizzano le informazioni sugli abbonamenti Keystone. Sebbene tutti questi utenti debbano monitorare l'iscrizione Keystone, solo il responsabile del team può effettuare richieste di servizio. A tre dei membri del team viene assegnato il ruolo *Keystone Viewer*, mentre al responsabile del team viene assegnato il ruolo *Keystone admin* in modo che vi sia un punto di controllo sulle richieste di servizio per l'azienda.

La tabella seguente indica le azioni che ogni ruolo Keystone può eseguire.

[cols="40,20a,20a"]
|===
| Funzione e azione | Amministratore Keystone | Visualizzatore Keystone 


| Visualizzare le seguenti schede: Abbonamento, risorse, monitoraggio e Amministrazione  a| 
Sì
 a| 
Sì



3+| *Pagina di iscrizione Keystone*: 


| Visualizzare le iscrizioni  a| 
Sì
 a| 
Sì



| Modificare o rinnovare gli abbonamenti  a| 
Sì
 a| 
No



3+| *Pagina risorse Keystone*: 


| Visualizza risorse  a| 
Sì
 a| 
Sì



| Gestione delle risorse  a| 
Sì
 a| 
No



3+| *Pagina degli avvisi Keystone*: 


| Visualizza avvisi  a| 
Sì
 a| 
No



| Gestire gli avvisi  a| 
Sì
 a| 
No



| Creare avvisi da soli  a| 
Sì
 a| 
Sì



3+| *Portafoglio digitale*: 


| Consente di visualizzare il portafoglio digitale  a| 
Sì
 a| 
Sì



3+| *Pagina dei report Keystone*: 


| Scarica i report  a| 
Sì
 a| 
Sì



| Gestire i report  a| 
Sì
 a| 
Sì



| Creare report per sé stessi  a| 
Sì
 a| 
Sì



3+| *Richieste di servizio*: 


| Creare richieste di servizio  a| 
Sì
 a| 
No



| Visualizzare le richieste di servizio create da qualsiasi utente all'interno dell'organizzazione  a| 
Sì
 a| 
Sì

|===