---
sidebar: sidebar 
permalink: reference-iam-predefined-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management 
summary: 'La gestione delle identità e degli accessi di BlueXP  include diversi ruoli predefiniti che è possibile assegnare ai membri dell"organizzazione.' 
---
= Ruoli e autorizzazioni IAM BlueXP  predefiniti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
BlueXP  Identity and Access Management (IAM) include diversi ruoli predefiniti che è possibile assegnare ai membri dell'organizzazione in diversi livelli della gerarchia delle risorse. Prima di assegnare questi ruoli, è necessario comprendere le autorizzazioni incluse in ciascun ruolo.



== Ruoli della piattaforma

BlueXP  IAM include due ruoli di piattaforma: Amministratore dell'organizzazione e cartella o Amministratore del progetto. La principale differenza tra i due ruoli della piattaforma BlueXP  IAM è l'ambito. Il ruolo di amministratore dell'organizzazione dispone delle autorizzazioni per tutte le cartelle e i progetti, mentre l'amministratore della cartella o del progetto dispone solo delle autorizzazioni per la cartella o il progetto a cui sono stati assegnati.

Il ruolo di amministratore cartella o progetto non può creare connettori.

Permessi::


[cols="24,19,19"]
|===
| Attività | Amministratore dell'organizzazione | Cartella o Amministratore progetto 


| Creare connettori | Sì | No 


| Creare, modificare o eliminare ambienti di lavoro (aggiungere o rilevare nuove risorse utilizzando BlueXP  Canvas) | Sì | Sì 


| Creare progetti/cartelle, incluse la ridenominazione, l'eliminazione e la modifica | Sì | Sì 


| Assegnare ruoli e aggiungere utenti | Sì | Sì 


| Associare risorse e connettori a cartelle e progetti | Sì | Sì 


| Gestire le credenziali da Impostazioni > credenziali | Sì | Sì 


| Visualizza la timeline di BlueXP  | Sì | Sì 


| Utilizza i servizi BlueXP  | Sì | Sì 


| Registrati BlueXP  per supportare e inviare i casi | Sì | Sì 
|===
Esempio di ruoli organizzativi in BlueXP  per una grande organizzazione multinazionale:: XYZ Corporation, una multinazionale, intende separare l'accesso alle risorse di storage dei dati in base alle aree geografiche: Nord America, Europa e Asia-Pacifico. Vogliono che ogni regione abbia il controllo esclusivo sulle proprie risorse, pur mantenendo una supervisione centralizzata.
+
--
A tal fine, una persona a cui è stato assegnato il ruolo di amministratore dell'organizzazione in BlueXP  di XYZ Corporation crea un ambiente di lavoro iniziale e quindi crea cartelle separate in BlueXP  per ciascuna regione. La cartella di ogni regione contiene progetti (con risorse associate) correlati a tale regione. L'amministratore dell'organizzazione assegna a un utente BlueXP  in ciascuna regione il ruolo di amministratore cartella/progetto.

Una volta completata la configurazione iniziale, gli amministratori regionali con il ruolo di amministratore cartella o progetto possono creare nuovi ambienti di lavoro e aggiungere utenti all'interno delle rispettive aree geografiche. Questi amministratori regionali possono anche aggiungere/rimuovere/rinominare cartelle e progetti a cui sono assegnati. L'amministratore dell'organizzazione eredita le autorizzazioni per qualsiasi nuovo ambiente di lavoro o risorsa, mantenendo la visibilità dell'utilizzo dello storage nell'intera organizzazione.

--




== Ruoli nei servizi dati

I ruoli dei servizi dati possono completare le proprie attività in qualsiasi progetto o cartella.



=== Amministratore SnapCenter

Descrizione:: Consente di eseguire il backup delle snapshot da cluster ONTAP on-premise utilizzando il backup e recovery di BlueXP  per le applicazioni.
Permessi:: Un membro che ha questo ruolo può completare le seguenti azioni in BlueXP :
+
--
* Completare qualsiasi azione da Backup e ripristino > applicazioni
* Gestire tutti gli ambienti di lavoro nei progetti e nelle cartelle per i quali dispongono delle autorizzazioni
* Utilizzare tutti i servizi BlueXP 


--




=== Visualizzatore di classificazione

Descrizione:: Consente di visualizzare i risultati delle scansioni di classificazione BlueXP .
Permessi:: Visualizzare le informazioni sulla conformità e generare report per le risorse a cui hanno l'autorizzazione di accedere. Questi utenti non possono abilitare o disabilitare la scansione di volumi, bucket o schemi di database.
+
--
Non sono disponibili altre azioni per un membro che ha questo ruolo.

--




== Link correlati

* link:concept-identity-and-access-management.html["Informazioni sulla gestione delle identità e degli accessi di BlueXP "]
* link:task-iam-get-started.html["Introduzione a BlueXP  IAM"]
* link:task-iam-manage-members-permissions.html["Gestire i membri BlueXP  e le relative autorizzazioni"]
* https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html["Ulteriori informazioni sull'API per BlueXP  IAM"^]

