---
sidebar: sidebar 
permalink: reference-ports-aws.html 
keywords: ports, security group, http, https, inbound, outbound 
summary: Il gruppo di sicurezza AWS per il connettore richiede regole sia in entrata che in uscita. BlueXP crea automaticamente questo gruppo di protezione quando si crea un connettore da BlueXP. È necessario impostare questo gruppo di protezione per tutte le altre opzioni di installazione. 
---
= Regole del gruppo di sicurezza in AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il gruppo di sicurezza AWS per il connettore richiede regole sia in entrata che in uscita. BlueXP crea automaticamente questo gruppo di protezione quando si crea un connettore da BlueXP. È necessario impostare questo gruppo di protezione per tutte le altre opzioni di installazione.



== Regole in entrata

[cols="10,10,80"]
|===
| Protocollo | Porta | Scopo 


| SSH | 22 | Fornisce l'accesso SSH all'host del connettore 


| HTTP | 80 | Fornisce l'accesso HTTP dai browser Web client all'interfaccia utente locale 


| HTTPS | 443 | Fornisce l'accesso HTTPS dai browser Web client all'interfaccia utente locale e le connessioni dall'istanza di classificazione BlueXP 


| TCP | 3128 | Fornisce a Cloud Volumes ONTAP l'accesso a Internet per inviare messaggi AutoSupport al supporto NetApp. È necessario aprire manualmente questa porta dopo l'implementazione. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-verify-autosupport.html["Scopri come il connettore viene utilizzato come proxy per i messaggi AutoSupport"^] 


| TCP | 9060, 9061 | Consente di abilitare e utilizzare la classificazione BlueXP e il backup e ripristino BlueXP nelle regioni governative. 
|===


== Regole in uscita

Il gruppo di protezione predefinito per il connettore apre tutto il traffico in uscita. Se questo è accettabile, attenersi alle regole di base per le chiamate in uscita. Se sono necessarie regole più rigide, utilizzare le regole avanzate in uscita.



=== Regole di base in uscita

Il gruppo di protezione predefinito per il connettore include le seguenti regole in uscita.

[cols="20,20,60"]
|===
| Protocollo | Porta | Scopo 


| Tutti i TCP | Tutto | Tutto il traffico in uscita 


| Tutti gli UDP | Tutto | Tutto il traffico in uscita 
|===


=== Regole avanzate in uscita

Se sono necessarie regole rigide per il traffico in uscita, è possibile utilizzare le seguenti informazioni per aprire solo le porte richieste per la comunicazione in uscita dal connettore.


NOTE: L'indirizzo IP di origine è l'host del connettore.

[cols="5*"]
|===
| Servizio | Protocollo | Porta | Destinazione | Scopo 


| Chiamate API e AutoSupport | HTTPS | 443 | LIF gestione cluster ONTAP e Internet in uscita | L'API chiama AWS, ONTAP, classificandosi BlueXP e inviando messaggi AutoSupport a NetApp 


.2+| Chiamate API | TCP | 3000 | Mediatore ONTAP ha | Comunicazione con il mediatore ONTAP ha 


| TCP | 8080 | Classificazione BlueXP | Eseguire una verifica dell'istanza di classificazione BlueXP durante l'implementazione 


| DNS | UDP | 53 | DNS | Utilizzato per la risoluzione DNS di BlueXP 
|===