---
sidebar: sidebar 
permalink: task-set-up-networking-on-prem.html 
keywords: networking, on prem networking, endpoints, urls, ports, ip address, proxy, proxy server, connections 
summary: 'Configura il tuo networking in modo che il connettore possa gestire risorse e processi all"interno del tuo ambiente di cloud ibrido. Ad esempio, è necessario assicurarsi che le connessioni siano disponibili per le reti di destinazione e che sia disponibile l"accesso a Internet in uscita.' 
---
= Configurare il networking on-premise
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Configura il tuo networking in modo che il connettore possa gestire risorse e processi all'interno del tuo ambiente di cloud ibrido. Ad esempio, è necessario assicurarsi che le connessioni siano disponibili per le reti di destinazione e che sia disponibile l'accesso a Internet in uscita.



== Connessioni alle reti di destinazione

Un connettore richiede una connessione di rete al tipo di ambiente di lavoro che si sta creando e ai servizi che si intende abilitare.

Ad esempio, se si desidera avviare Cloud Volumes ONTAP nel cloud, è necessario impostare una connessione VPN dalla rete aziendale alla rete virtuale in cui si intende avviare Cloud Volumes ONTAP.



== Accesso a Internet in uscita

La posizione di rete in cui si implementa il connettore deve disporre di una connessione Internet in uscita.



=== Endpoint contattati durante l'installazione manuale

Quando si installa manualmente il connettore sul proprio host Linux, il programma di installazione del connettore richiede l'accesso ai seguenti URL durante il processo di installazione:

* \https://support.netapp.com
* \https://mysupport.netapp.com
* \https://cloudmanager.cloud.netapp.com/tenancy
* \https://stream.cloudmanager.cloud.netapp.com
* \https://production-artifacts.cloudmanager.cloud.netapp.com
* \https://*.blob.core.windows.net
* \https://cloudmanagerinfraprod.azurecr.io


L'host potrebbe tentare di aggiornare i pacchetti del sistema operativo durante l'installazione. L'host può contattare diversi siti di mirroring per questi pacchetti di sistemi operativi.



=== Endpoint contattati dal connettore

Il connettore richiede l'accesso a Internet in uscita per contattare i seguenti endpoint al fine di gestire risorse e processi all'interno dell'ambiente di cloud pubblico per le operazioni quotidiane.

[cols="2a,1a"]
|===
| Endpoint | Scopo 


 a| 
Servizi AWS (amazonaws.com):

* CloudFormation
* Elastic Compute Cloud (EC2)
* Gestione delle identità e degli accessi (IAM)
* Servizio di gestione delle chiavi (KMS)
* Servizio token di sicurezza (STS)
* S3 (Simple Storage Service)

 a| 
Per gestire le risorse in AWS. L'endpoint esatto dipende dalla regione in cui viene implementato il connettore. https://docs.aws.amazon.com/general/latest/gr/rande.html["Per ulteriori informazioni, fare riferimento alla documentazione AWS"^]



 a| 
\https://management.azure.com
\https://login.microsoftonline.com
\https://blob.core.windows.net
\https://core.windows.net
 a| 
Per gestire le risorse nelle aree pubbliche di Azure.



 a| 
\https://management.chinacloudapi.cn
\https://login.chinacloudapi.cn
\https://blob.core.chinacloudapi.cn
\https://core.chinacloudapi.cn
 a| 
Per gestire le risorse nelle regioni Azure China.



 a| 
\https://www.googleapis.com/compute/v1/
\https://compute.googleapis.com/compute/v1
\https://cloudresourcemanager.googleapis.com/v1/projects
\https://www.googleapis.com/compute/beta
\https://storage.googleapis.com/storage/v1
\https://www.googleapis.com/storage/v1
\https://iam.googleapis.com/v1
\https://cloudkms.googleapis.com/v1
\https://www.googleapis.com/deploymentmanager/v2/projects
 a| 
Per gestire le risorse in Google Cloud.



 a| 
\https://support.netapp.com
 a| 
Per ottenere informazioni sulle licenze e inviare messaggi AutoSupport al supporto NetApp.



 a| 
\https://*.api.bluexp.netapp.com

\https://api.bluexp.netapp.com

\https://*.cloudmanager.cloud.netapp.com

\https://cloudmanager.cloud.netapp.com
 a| 
Fornire funzionalità e servizi SaaS all'interno di BlueXP.


NOTE: Il connettore sta attualmente contattando "cloudmanager.cloud.netapp.com", ma inizierà a contattare "api.bluexp.netapp.com" in una versione successiva.



 a| 
\https://*.blob.core.windows.net

\https://cloudmanagerinfraprod.azurecr.io
 a| 
Per aggiornare il connettore e i relativi componenti Docker.

|===
.Link correlato
link:reference-networking-saas-console.html["Preparare la rete per l'accesso dell'utente alla console BlueXP"]



== Server proxy

Se l'organizzazione richiede la distribuzione di un server proxy per tutto il traffico Internet in uscita, ottenere le seguenti informazioni sul proxy HTTP o HTTPS:

* Indirizzo IP
* Credenziali
* Certificato HTTPS


Queste informazioni devono essere fornite durante l'installazione.



== Porte

Non c'è traffico in entrata verso il connettore, a meno che non venga avviato o se il connettore viene utilizzato come proxy per inviare messaggi AutoSupport da Cloud Volumes ONTAP al supporto NetApp.

* HTTP (80) e HTTPS (443) forniscono l'accesso all'interfaccia utente locale, che verrà utilizzata in rare circostanze.
* SSH (22) è necessario solo se è necessario connettersi all'host per la risoluzione dei problemi.
* Le connessioni in entrata sulla porta 3128 sono necessarie se si implementano sistemi Cloud Volumes ONTAP in una subnet in cui non è disponibile una connessione Internet in uscita.
+
Se i sistemi Cloud Volumes ONTAP non dispongono di una connessione Internet in uscita per inviare messaggi AutoSupport, BlueXP configura automaticamente i sistemi Cloud Volumes ONTAP in modo che utilizzino un server proxy incluso nel connettore. L'unico requisito è garantire che il gruppo di sicurezza del connettore consenta le connessioni in entrata sulla porta 3128. Dopo aver implementato il connettore, aprire questa porta.





== Limitazione dell'indirizzo IP

È possibile che vi sia un conflitto con gli indirizzi IP nell'intervallo 172. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-limitations.html["Scopri di più su questo limite"].
