---
sidebar: sidebar 
permalink: task-set-up-permissions-aws.html 
keywords: aws permissions, set up permissions, set up aws permissions, permissions, iam role, iam policy, json, policy, role, credentials 
summary: 'Impostare le autorizzazioni in AWS in modo da poter implementare il connettore con le autorizzazioni necessarie per gestire l"infrastruttura di dati e storage. Le modalità di impostazione e di fornitura delle autorizzazioni dipendono dall"opzione di installazione che si intende utilizzare.' 
---
= Impostare le autorizzazioni AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Impostare le autorizzazioni in AWS in modo da poter implementare il connettore con le autorizzazioni necessarie per gestire l'infrastruttura di dati e storage. Le modalità di impostazione e di fornitura delle autorizzazioni dipendono dall'opzione di installazione che si intende utilizzare.

È possibile scegliere tra le seguenti opzioni di installazione:

* *Installa da BlueXP*: Imposta le autorizzazioni che consentono a BlueXP di autenticare con AWS e distribuire l'istanza. BlueXP imposta automaticamente le autorizzazioni per l'istanza del connettore durante l'implementazione.
+
<<Impostare le autorizzazioni per creare il connettore da BlueXP,Visualizza istruzioni dettagliate>>.

* *Installa da AWS Marketplace*: Imposta un ruolo IAM che puoi associare all'istanza di Connector.
+
<<Impostare le autorizzazioni per il connettore durante l'implementazione da AWS Marketplace,Visualizza istruzioni dettagliate>>.

* *Installazione manuale*: Creare policy IAM e allegarle a un ruolo IAM o a un utente IAM.
+
<<Impostare le autorizzazioni da assegnare dopo l'installazione manuale,Visualizza istruzioni dettagliate>>.





== Impostare le autorizzazioni per creare il connettore da BlueXP

BlueXP deve eseguire l'autenticazione con AWS prima di poter implementare l'istanza del connettore nel VPC. È possibile scegliere uno dei seguenti metodi di autenticazione:

* Lasciare che BlueXP assuma un ruolo IAM con le autorizzazioni richieste
* Fornire una chiave di accesso AWS e una chiave segreta per un utente IAM che dispone delle autorizzazioni richieste


Con entrambe le opzioni, il primo passo è creare un criterio IAM. Questo criterio contiene solo le autorizzazioni necessarie per avviare l'istanza di Connector in AWS da BlueXP.

Se necessario, è possibile limitare la policy IAM utilizzando il modulo IAM `Condition` elemento. https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition.html["Documentazione AWS: Elemento Condition"^]


TIP: Quando BlueXP crea il connettore, applica un nuovo set di autorizzazioni all'istanza del connettore che consente al connettore di gestire le risorse AWS.

.Fasi
. Accedere alla console AWS IAM.
. Fare clic su *Policy > Create policy* (Criteri > Crea policy).
. Fare clic su *JSON*.
. Copiare e incollare il seguente criterio:
+
Si ricorda che questo criterio contiene solo le autorizzazioni necessarie per avviare l'istanza di Connector in AWS da BlueXP. link:reference-permissions-aws.html["Visualizza le autorizzazioni richieste per l'istanza del connettore"].

+
[source, json]
----
{
    "Version": "2012-10-17",
    "Statement": [{
            "Effect": "Allow",
            "Action": [
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:PutRolePolicy",
                "iam:CreateInstanceProfile",
                "iam:DeleteRolePolicy",
                "iam:AddRoleToInstanceProfile",
                "iam:RemoveRoleFromInstanceProfile",
                "iam:DeleteInstanceProfile",
                "iam:PassRole",
                "ec2:DescribeInstanceStatus",
                "ec2:RunInstances",
                "ec2:ModifyInstanceAttribute",
                "ec2:CreateSecurityGroup",
                "ec2:DeleteSecurityGroup",
                "ec2:DescribeSecurityGroups",
                "ec2:RevokeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:RevokeSecurityGroupIngress",
                "ec2:CreateNetworkInterface",
                "ec2:DescribeNetworkInterfaces",
                "ec2:DeleteNetworkInterface",
                "ec2:ModifyNetworkInterfaceAttribute",
                "ec2:DescribeSubnets",
                "ec2:DescribeVpcs",
                "ec2:DescribeDhcpOptions",
                "ec2:DescribeKeyPairs",
                "ec2:DescribeRegions",
                "ec2:DescribeInstances",
                "ec2:CreateTags",
                "ec2:DescribeImages",
                "cloudformation:CreateStack",
                "cloudformation:DeleteStack",
                "cloudformation:DescribeStacks",
                "cloudformation:DescribeStackEvents",
                "cloudformation:ValidateTemplate",
                "ec2:AssociateIamInstanceProfile",
                "ec2:DescribeIamInstanceProfileAssociations",
                "ec2:DisassociateIamInstanceProfile",
                "iam:GetRole",
                "iam:TagRole",
                "iam:ListRoles",
                "kms:ListAliases"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "ec2:TerminateInstances"
            ],
            "Condition": {
                "StringLike": {
                    "ec2:ResourceTag/OCCMInstance": "*"
                }
            },
            "Resource": [
                "arn:aws:ec2:*:*:instance/*"
            ]
        }
    ]
}
----
. Fare clic su *Avanti* e aggiungere tag, se necessario.
. Fare clic su *Avanti* e immettere un nome e una descrizione.
. Fare clic su *Crea policy*.
. Allegare il criterio a un ruolo IAM che BlueXP può assumere o a un utente IAM in modo da poter fornire a BlueXP le chiavi di accesso:
+
** (Opzione 1) impostare un ruolo IAM che BlueXP può assumere:
+
... Accedere alla console AWS IAM nell'account di destinazione.
... In Gestione accessi, fare clic su *ruoli > Crea ruolo* e seguire i passaggi per creare il ruolo.
... In *Trusted entity type*, selezionare *AWS account*.
... Selezionare *un altro account AWS* e inserire l'ID dell'account BlueXP SaaS: 952013314444
... Selezionare il criterio creato nella sezione precedente.
... Dopo aver creato il ruolo, copiare l'ARN del ruolo in modo da poterlo incollare in BlueXP quando si crea il connettore.


** (Opzione 2) impostare le autorizzazioni per un utente IAM in modo da poter fornire a BlueXP le chiavi di accesso:
+
... Dalla console di AWS IAM, fare clic su *Users* (utenti), quindi selezionare il nome utente.
... Fare clic su *Aggiungi permessi > Allega direttamente policy esistenti*.
... Selezionare il criterio creato.
... Fare clic su *Avanti*, quindi su *Aggiungi permessi*.
... Assicurarsi di disporre della chiave di accesso e della chiave segreta per l'utente IAM.






.Risultato
Ora dovresti disporre di un ruolo IAM con le autorizzazioni richieste o di un utente IAM con le autorizzazioni richieste. Quando si crea il connettore da BlueXP, è possibile fornire informazioni sul ruolo o sulle chiavi di accesso.



== Impostare le autorizzazioni per il connettore durante l'implementazione da AWS Marketplace

Per prepararsi all'implementazione di un marketplace, creare policy IAM in AWS e allegarle a un ruolo IAM. Quando si crea il connettore da AWS Marketplace, viene richiesto di selezionare il ruolo IAM.

.Fasi
. Accedere alla console AWS e accedere al servizio IAM.
. Creare una policy:
+
.. Fare clic su *Policy > Create policy* (Criteri > Crea policy).
.. Selezionare *JSON* e copiare e incollare il contenuto di link:reference-permissions-aws.html["Policy IAM per il connettore"].
.. Completare i passaggi rimanenti per creare il criterio.
+
A seconda dei servizi BlueXP che si intende utilizzare, potrebbe essere necessario creare una seconda policy. Per le regioni standard, le autorizzazioni sono distribuite in due policy. Sono necessarie due policy a causa di un limite massimo di dimensioni dei caratteri per le policy gestite in AWS. link:reference-permissions-aws.html["Scopri di più sulle policy IAM per il connettore"].



. Creare un ruolo IAM:
+
.. Fare clic su *ruoli > Crea ruolo*.
.. Selezionare *servizio AWS > EC2*.
.. Aggiungere le autorizzazioni allegando il criterio appena creato.
.. Completare i passaggi rimanenti per creare il ruolo.




.Risultato
Ora si dispone di un ruolo IAM che è possibile associare all'istanza EC2 durante la distribuzione da AWS Marketplace.



== Impostare le autorizzazioni da assegnare dopo l'installazione manuale

Se si prevede di installare manualmente il software del connettore sul proprio host Linux in AWS, è possibile fornire le autorizzazioni nei seguenti modi:

* Opzione 1: Creazione di criteri IAM e associazione dei criteri a un ruolo IAM che è possibile associare all'istanza EC2.
* Opzione 2: Fornire a BlueXP le chiavi di accesso AWS per un utente IAM che dispone delle autorizzazioni necessarie.


[role="tabbed-block"]
====
.Ruolo IAM
--
.Fasi
. Accedere alla console AWS e accedere al servizio IAM.
. Creare una policy:
+
.. Fare clic su *Policy > Create policy* (Criteri > Crea policy).
.. Selezionare *JSON* e copiare e incollare il contenuto di link:reference-permissions-aws.html["Policy IAM per il connettore"].
.. Completare i passaggi rimanenti per creare il criterio.
+
A seconda dei servizi BlueXP che si intende utilizzare, potrebbe essere necessario creare una seconda policy. Per le regioni standard, le autorizzazioni sono distribuite in due policy. Sono necessarie due policy a causa di un limite massimo di dimensioni dei caratteri per le policy gestite in AWS. link:reference-permissions-aws.html["Scopri di più sulle policy IAM per il connettore"].



. Creare un ruolo IAM:
+
.. Fare clic su *ruoli > Crea ruolo*.
.. Selezionare *servizio AWS > EC2*.
.. Aggiungere le autorizzazioni allegando il criterio appena creato.
.. Completare i passaggi rimanenti per creare il ruolo.




.Risultato
Ora si dispone di un ruolo IAM che è possibile associare all'istanza EC2 dopo aver installato il connettore. link:task-provide-permissions-aws.html["Scopri come fornire queste autorizzazioni a BlueXP"].

--
.Chiave di accesso AWS
--
.Fasi
. Accedere alla console AWS e accedere al servizio IAM.
. Creare una policy:
+
.. Fare clic su *Policy > Create policy* (Criteri > Crea policy).
.. Selezionare *JSON* e copiare e incollare il contenuto di link:reference-permissions-aws.html["Policy IAM per il connettore"].
.. Completare i passaggi rimanenti per creare il criterio.
+
A seconda dei servizi BlueXP che si intende utilizzare, potrebbe essere necessario creare una seconda policy.

+
Per le regioni standard, le autorizzazioni sono distribuite in due policy. Sono necessarie due policy a causa di un limite massimo di dimensioni dei caratteri per le policy gestite in AWS. link:reference-permissions-aws.html["Scopri di più sulle policy IAM per il connettore"].



. Allegare i criteri a un utente IAM.
+
** https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create.html["Documentazione AWS: Creazione dei ruoli IAM"^]
** https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_manage-attach-detach.html["Documentazione di AWS: Aggiunta e rimozione dei criteri IAM"^]


. Assicurarsi che l'utente disponga di una chiave di accesso che è possibile aggiungere a BlueXP dopo aver installato il connettore.


.Risultato
Ora si dispone di un utente IAM che dispone delle autorizzazioni necessarie e di una chiave di accesso che è possibile fornire a BlueXP. link:task-provide-permissions-aws.html["Scopri come fornire queste autorizzazioni a BlueXP"].

--
====