---
sidebar: sidebar 
permalink: task-provide-permissions-google.html 
keywords: google cloud permissions, permissions, gcp permissions, service account, gcp service account 
summary: 'Se il software del connettore è stato installato manualmente sul proprio host Linux, è necessario fornire a BlueXP i permessi precedentemente impostati. La fornitura delle autorizzazioni consente a BlueXP di gestire l"infrastruttura di dati e storage in Google Cloud.' 
---
= Fornire le autorizzazioni Google Cloud a BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se il software del connettore è stato installato manualmente sul proprio host Linux, è necessario fornire a BlueXP i permessi precedentemente impostati. La fornitura delle autorizzazioni consente a BlueXP di gestire l'infrastruttura di dati e storage in Google Cloud.

link:task-set-up-permissions-google.html["Scopri come impostare queste autorizzazioni"].

Questi passaggi non si applicano se il connettore è stato implementato direttamente da BlueXP o utilizzando gcloud.

.Fasi
. Accedere al portale Google Cloud e assegnare l'account del servizio all'istanza della macchina virtuale del connettore.
+
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes["Documentazione di Google Cloud: Modifica dell'account del servizio e degli ambiti di accesso per un'istanza"^]

. Se si desidera distribuire Cloud Volumes ONTAP in altri progetti, concedere l'accesso aggiungendo l'account di servizio con il ruolo BlueXP a tale progetto. Dovrai ripetere questo passaggio per ogni progetto.


.Risultato
BlueXP dispone ora delle autorizzazioni necessarie per eseguire azioni in Google Cloud per tuo conto.
