---
sidebar: sidebar 
permalink: task-upgrade-connector.html 
keywords: upgrade, manual upgrade, connector upgrade, manual connector upgrade, upgrade connector manually, private mode upgrade, offline upgrade, upgrade private mode 
summary: 'BlueXP aggiorna automaticamente un connettore all"ultima release quando utilizzi BlueXP in modalità standard o limitata. Le nuove versioni vengono in genere rilasciate ogni mese per introdurre nuove funzionalità e fornire miglioramenti alla stabilità. Se si preferisce, è possibile configurare il connettore in modo che estragga gli aggiornamenti delle immagini da un repository locale. Per le implementazioni in modalità privata, è sempre necessario aggiornare manualmente il connettore.' 
---
= Gestire gli aggiornamenti dei connettori
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando si utilizza BlueXP  in modalità standard o limitata, BlueXP  aggiorna automaticamente il connettore all'ultima versione, purché disponga dell'accesso a Internet in uscita per ottenere l'aggiornamento software. Se è necessario gestire manualmente quando il connettore viene aggiornato, è possibile disattivare gli aggiornamenti automatici per la modalità standard o limitata.


NOTE: Quando si esegue BlueXP  in modalità privata, è sempre necessario aggiornare il connettore.



== Disattivare gli aggiornamenti automatici

La disattivazione dell'aggiornamento automatico del connettore consiste in due fasi. Innanzitutto, è necessario assicurarsi che il connettore sia sano e aggiornato. Quindi, si modificherà un file di configurazione per disattivare la funzione di aggiornamento automatico.


NOTE: È possibile disattivare gli aggiornamenti automatici solo se si dispone della versione 3.9.48 o superiore del connettore.



=== Verificare lo stato del connettore

È necessario verificare che il connettore sia stabile e che tutti i contenitori in esecuzione sulla macchina virtuale del connettore siano funzionanti. Dopo aver disattivato gli aggiornamenti automatici, la macchina virtuale del connettore smette di cercare nuovi servizi o pacchetti di aggiornamento.

Utilizzare uno dei seguenti comandi per verificare il connettore. Tutti i servizi devono avere lo stato _running_. In caso contrario, contattare l'assistenza NetApp prima di disattivare l'aggiornamento automatico.

Docker::
+
--
[source, cli]
----
docker ps -a
----
--
Podman::
+
--
[source, cli]
----
podman ps -a
----
--




=== Disattivare l'aggiornamento automatico per il connettore

Per disabilitare gli aggiornamenti automatici, impostare il flag _isUpgradeDisabled_ nel file _com/opt/application/NetApp/service-manager-2/config.json_. Per impostazione predefinita, questo flag è impostato su false e il connettore viene aggiornato automaticamente. È possibile impostare questo flag su true per disabilitare gli aggiornamenti automatici. Prima di completare questo passaggio, è necessario conoscere la sintassi JSON.

Per riattivare l'aggiornamento automatico, procedere come segue e impostare il flag _isUpgradeDisabled_ su false.

.Fasi
. Assicurarsi di aver verificato che il connettore sia aggiornato e integro.
. Creare una copia di backup del file _/opt/application/NetApp/service-manager-2/config.json_ per assicurarsi di poter ripristinare le modifiche.
. Modificare il file _/opt/application/NetApp/service-manager-2/config.json_ e impostare il valore del flag _isUpgradeDisabled_ su true.
+
[source]
----
  "isUpgradeDisabled": true,
----
. Salvare il file.
. Riavviare il servizio Service Manager 2 eseguendo il seguente comando:
+
[source, cli]
----
systemctl restart netapp-service-manager.service
----
. Eseguire il seguente comando e verificare che lo stato del connettore sia _Active(Running)_: _
+
[source, cli]
----
systemctl status netapp-service-manager.service
----




== Aggiornare il connettore

Il connettore deve essere riavviato durante il processo di aggiornamento, in modo che la console basata su Web non sia disponibile durante l'aggiornamento.

.Fasi
. Scaricare il software del connettore da https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Sito di supporto NetApp"^].
+
Assicurarsi di scaricare il programma di installazione offline per le reti private senza accesso a Internet.

. Copiare il programma di installazione sull'host Linux.
. Assegnare le autorizzazioni per eseguire lo script.
+
[source, cli]
----
chmod +x /path/BlueXP-Connector-offline-<version>
----
+
Dove <version> è la versione del connettore scaricato.

. Eseguire lo script di installazione:
+
[source, cli]
----
sudo /path/BlueXP-Connector-offline-<version>
----
+
Dove <version> è la versione del connettore scaricato.

. Una volta completato l'aggiornamento, è possibile verificare la versione del connettore accedendo a *Guida > supporto tecnico > connettore*.

