---
sidebar: sidebar 
permalink: task-set-up-permissions-google.html 
keywords: set up permissions, set up gcp permissions, set up google cloud permissions, google permissions, gcp permissions, service account, create service account, gcp service account, google service account 
summary: 'Impostare le autorizzazioni di Google Cloud in modo da poter utilizzare BlueXP per gestire l"infrastruttura di dati e storage in Google Cloud.' 
---
= Impostare le autorizzazioni di Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Impostare le autorizzazioni in Google Cloud in modo da poter implementare il connettore con le autorizzazioni necessarie per gestire l'infrastruttura di dati e storage.

Devi impostare le autorizzazioni Google Cloud come segue:

* Se si intende creare il connettore da BlueXP o utilizzando gcloud, è necessario impostare le autorizzazioni per l'utente di Google Cloud che implementerà la macchina virtuale del connettore.
* Impostare le autorizzazioni per il connettore creando un ruolo e concedendo il ruolo a un account di servizio.
+
L'account del servizio verrà associato alla macchina virtuale del connettore in modo che BlueXP disponga delle autorizzazioni necessarie.



A seconda della configurazione, potrebbe essere necessario completare anche i seguenti passaggi:

* Impostare le autorizzazioni tra i progetti
* Impostare le autorizzazioni per un VPC condiviso




== Impostare le autorizzazioni per creare il connettore da BlueXP o gcloud

Prima di poter implementare un connettore da BlueXP o utilizzando gcloud, è necessario assicurarsi che l'account Google Cloud disponga delle autorizzazioni corrette.

.Fasi
. Creare un ruolo personalizzato in Google Cloud:
+
.. Creare un file YAML che includa le seguenti autorizzazioni:
+
[source, yaml]
----
title: Connector deployment policy
description: Permissions for the user who deploys the Connector from BlueXP
stage: GA
includedPermissions:
- compute.disks.create
- compute.disks.get
- compute.disks.list
- compute.disks.setLabels
- compute.disks.use
- compute.firewalls.create
- compute.firewalls.delete
- compute.firewalls.get
- compute.firewalls.list
- compute.globalOperations.get
- compute.images.get
- compute.images.getFromFamily
- compute.images.list
- compute.images.useReadOnly
- compute.instances.attachDisk
- compute.instances.create
- compute.instances.get
- compute.instances.list
- compute.instances.setDeletionProtection
- compute.instances.setLabels
- compute.instances.setMachineType
- compute.instances.setMetadata
- compute.instances.setTags
- compute.instances.start
- compute.instances.updateDisplayDevice
- compute.machineTypes.get
- compute.networks.get
- compute.networks.list
- compute.networks.updatePolicy
- compute.projects.get
- compute.regions.get
- compute.regions.list
- compute.subnetworks.get
- compute.subnetworks.list
- compute.zoneOperations.get
- compute.zones.get
- compute.zones.list
- deploymentmanager.compositeTypes.get
- deploymentmanager.compositeTypes.list
- deploymentmanager.deployments.create
- deploymentmanager.deployments.delete
- deploymentmanager.deployments.get
- deploymentmanager.deployments.list
- deploymentmanager.manifests.get
- deploymentmanager.manifests.list
- deploymentmanager.operations.get
- deploymentmanager.operations.list
- deploymentmanager.resources.get
- deploymentmanager.resources.list
- deploymentmanager.typeProviders.get
- deploymentmanager.typeProviders.list
- deploymentmanager.types.get
- deploymentmanager.types.list
- resourcemanager.projects.get
- compute.instances.setServiceAccount
- iam.serviceAccounts.list
----
.. Da Google Cloud, attiva la shell cloud.
.. Caricare il file YAML che include le autorizzazioni richieste.
.. Creare un ruolo personalizzato utilizzando `gcloud iam roles create` comando.
+
Nell'esempio seguente viene creato un ruolo denominato "connectorDeployment" a livello di progetto:

+
I ruoli iam di gcloud creano connectorDeployment --project=myproject --file=Connector-deployment.yaml

+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Documenti Google Cloud: Creazione e gestione di ruoli personalizzati"^]



. Assegnare questo ruolo personalizzato all'utente che implementerà il connettore da BlueXP o utilizzando gcloud.
+
https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Documenti di Google Cloud: Assegnare un singolo ruolo"^]



.Risultato
L'utente di Google Cloud dispone ora delle autorizzazioni necessarie per creare il connettore.



== Impostare le autorizzazioni per il connettore

È necessario un account di servizio per fornire al connettore le autorizzazioni necessarie a BlueXP per gestire le risorse in Google Cloud. È necessario associare questo account di servizio alla macchina virtuale del connettore.

.Fasi
. Creare un ruolo personalizzato in Google Cloud:
+
.. Creare un file YAML che includa il contenuto di link:reference-permissions-gcp.html["Autorizzazioni dell'account di servizio per il connettore"].
.. Da Google Cloud, attiva la shell cloud.
.. Caricare il file YAML che include le autorizzazioni richieste.
.. Creare un ruolo personalizzato utilizzando `gcloud iam roles create` comando.
+
Nell'esempio seguente viene creato un ruolo denominato "Connector" a livello di progetto:

+
`gcloud iam roles create connector --project=myproject --file=connector.yaml`

+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Documenti Google Cloud: Creazione e gestione di ruoli personalizzati"^]



. Creare un account di servizio in Google Cloud:
+
.. Dal servizio IAM & Admin, fare clic su *account di servizio > Crea account di servizio*.
.. Inserire i dettagli dell'account del servizio e fare clic su *Create and Continue* (Crea e continua).
.. Selezionare il ruolo appena creato.
.. Completare i passaggi rimanenti per creare il ruolo.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Documenti Google Cloud: Creazione di un account di servizio"^]





.Risultato
L'account di servizio per la macchina virtuale del connettore è impostato.



== Impostare le autorizzazioni tra i progetti

Se si prevede di implementare i sistemi Cloud Volumes ONTAP in progetti diversi da quello in cui si trova il connettore, è necessario fornire l'account di servizio del connettore per accedere a tali progetti.

Ad esempio, supponiamo che il connettore si trovi nel progetto 1 e che si desideri creare sistemi Cloud Volumes ONTAP nel progetto 2. È necessario concedere l'accesso all'account di servizio nel progetto 2.

.Fasi
. Nella console di Google Cloud, accedere al servizio IAM e selezionare il progetto in cui si desidera creare i sistemi Cloud Volumes ONTAP.
. Nella pagina *IAM*, selezionare *Concedi accesso* e fornire i dettagli richiesti.
+
** Inserire l'indirizzo e-mail dell'account di servizio del connettore.
** Selezionare il ruolo personalizzato del connettore.
** Fare clic su *Save* (Salva).




Per ulteriori informazioni, fare riferimento a. https://cloud.google.com/iam/docs/granting-changing-revoking-access#grant-single-role["Documentazione di Google Cloud"^]



== Impostare le autorizzazioni VPC condivise

Se si utilizza un VPC condiviso per distribuire le risorse in un progetto di servizio, è necessario preparare le autorizzazioni.

Questa tabella è di riferimento e l'ambiente deve riflettere la tabella delle autorizzazioni al termine della configurazione IAM.

[cols="10,10,10,20,20,30"]
|===
| Identità | Creatore | Ospitato in | Permessi del progetto di servizio | Permessi del progetto host | Scopo 


| Google per implementare il connettore | Personalizzato | Progetto di servizio  a| 
link:task-set-up-permissions-google.html#set-up-permissions-to-create-the-connector-from-bluexp-or-gcloud["Policy di implementazione del connettore"]
 a| 
compute.networkUser
| Implementazione del connettore nel progetto di servizio 


| Account del servizio Connector | Personalizzato | Progetto di servizio  a| 
link:reference-permissions-gcp.html["Policy dell'account di servizio del connettore"]
 a| 
* compute.networkUser
* deploymentmanager.editor

| Implementazione e manutenzione di Cloud Volumes ONTAP e servizi nel progetto di servizio 


| Account del servizio Cloud Volumes ONTAP | Personalizzato | Progetto di servizio  a| 
* storage.admin
* membro: Account di servizio BlueXP come serviceAccount.user

| N/A. | (Opzionale) per il tiering dei dati e il backup e ripristino BlueXP 


| Agente del servizio API di Google | Google Cloud | Progetto di servizio  a| 
(Impostazione predefinita) Editor
 a| 
compute.networkUser
| Interagisce con le API di Google Cloud per conto dell'implementazione. Consente a BlueXP di utilizzare la rete condivisa. 


| Account di servizio predefinito di Google Compute Engine | Google Cloud | Progetto di servizio  a| 
(Impostazione predefinita) Editor
 a| 
compute.networkUser
| Implementa le istanze di Google Cloud e l'infrastruttura di calcolo per conto dell'implementazione. Consente a BlueXP di utilizzare la rete condivisa. 
|===
Note:

. Deploymentmanager.editor è necessario solo per il progetto host se non si passano le regole del firewall alla distribuzione e si sceglie di consentire a BlueXP di crearle. BlueXP crea una distribuzione nel progetto host che contiene la regola firewall VPC0 se non viene specificata alcuna regola.
. Firewall.create e firewall.delete sono necessari solo se non si passano le regole firewall all'implementazione e si sceglie di consentire a BlueXP di crearle. Queste autorizzazioni risiedono nel file .yaml dell'account BlueXP. Se si implementa una coppia ha utilizzando un VPC condiviso, queste autorizzazioni verranno utilizzate per creare le regole firewall per VPC1, 2 e 3. Per tutte le altre implementazioni, queste autorizzazioni verranno utilizzate anche per creare regole per VPC0.
. Per il tiering dei dati, l'account del servizio di tiering deve avere il ruolo serviceAccount.user nell'account del servizio, non solo a livello di progetto. Attualmente, se si assegna serviceAccount.user a livello di progetto, le autorizzazioni non vengono visualizzate quando si esegue una query all'account del servizio con getIAMPolicy.

