---
sidebar: sidebar 
permalink: task-create-account.html 
keywords: create account, account, create, create another account, tenancy account, tenancy, tenancy account creation 
summary: 'Quando si imposta BlueXP  in modalità limitata o privata, viene richiesto di creare un account. Se sono necessari più account, è necessario crearli utilizzando l"API tenancy.' 
---
= Creare un altro account BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando si imposta BlueXP  in modalità privata, viene richiesto di creare un _account BlueXP _, che consente di gestire gli utenti e organizzare le risorse. Questo account potrebbe essere tutto ciò di cui hai bisogno, ma se la tua azienda richiede più account, dovrai creare altri account utilizzando l'API tenancy.

Se utilizzi BlueXP  in modalità standard o con restrizioni, non avrai un account BlueXP . Al contrario, avrete un'organizzazione che gestite utilizzando la gestione delle identità e degli accessi (IAM, Identity and Access Management) di BlueXP . link:concept-identity-and-access-management.html["Ulteriori informazioni su BlueXP  IAM"].

.Fasi
. Utilizzare la seguente chiamata API per creare un account BlueXP aggiuntivo:
+
POST `/tenancy/account/{accountName}`

+
Se si desidera attivare la modalità limitata, è necessario includere quanto segue nel corpo della richiesta:

+
[source, JSON]
----
{
  "isSaasDisabled": true
}
----



NOTE: Non è possibile modificare l'impostazione della modalità limitata dopo che BlueXP ha creato l'account. Non puoi attivare la modalità limitata in un secondo momento e non puoi disattivarla in un secondo momento. Deve essere impostato al momento della creazione dell'account.

https://docs.netapp.com/us-en/bluexp-automation/tenancy/post-tenancy-account-id.html["Scopri come utilizzare questa chiamata API"^]

.Informazioni correlate
* link:concept-netapp-accounts.html["Scopri di più sugli account BlueXP"]
* link:concept-modes.html["Scopri le modalità di implementazione di BlueXP"]

