---
sidebar: sidebar 
permalink: task-logging-in.html 
keywords: logging in, log in, sign in, signing in, cloud central, netapp cloud central, user account, federated, federation, federated login, federation login, login with netapp, log in with netapp, sign up, create account 
summary: 'Il modo in cui accedi ad BlueXP dipende dalla modalità di implementazione di BlueXP che stai utilizzando per l"account.' 
---
= Accedere a BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il modo in cui accedi ad BlueXP dipende dalla modalità di implementazione di BlueXP che stai utilizzando per l'account.

[role="tabbed-block"]
====
.Modalità standard
--
Dopo aver effettuato la registrazione a BlueXP, è possibile accedere dalla console basata su Web per iniziare a gestire l'infrastruttura di dati e storage.

.A proposito di questa attività
È possibile accedere alla console basata su Web di BlueXP utilizzando una delle seguenti opzioni:

* Le tue credenziali NetApp Support Site (NSS) esistenti
* Un login cloud NetApp utilizzando il tuo indirizzo e-mail e una password
* Una connessione federata
+
È possibile utilizzare il Single Sign-on per accedere utilizzando le credenziali della directory aziendale (identità federata). link:concept-federation.html["Scopri come utilizzare la federazione delle identità con BlueXP"].



.Fasi
. Aprire un browser Web e accedere a. https://console.bluexp.netapp.com["Console BlueXP"^]
. Nella pagina *Log in*, inserire l'indirizzo e-mail associato al login.
. A seconda del metodo di autenticazione associato all'accesso, viene richiesto di inserire le credenziali:
+
** Credenziali cloud NetApp: Inserire la password
** Federated User (utente federato): Immettere le credenziali di identità federated
** Account NetApp Support Site: Immettere le credenziali del NetApp Support Site




.Risultato
Ora hai effettuato l'accesso e puoi iniziare a utilizzare BlueXP per gestire la tua infrastruttura multi-cloud ibrida.

--
.Modalità limitata
--
Quando si utilizza BlueXP in modalità limitata, è necessario accedere alla console BlueXP dall'interfaccia utente che viene eseguita localmente sul connettore.

.A proposito di questa attività
BlueXP supporta l'accesso con una delle seguenti opzioni quando l'account è impostato in modalità limitata:

* Un login cloud NetApp utilizzando il tuo indirizzo e-mail e una password
* Una connessione federata
+
È possibile utilizzare il Single Sign-on per accedere utilizzando le credenziali della directory aziendale (identità federata). link:concept-federation.html["Scopri come utilizzare la federazione delle identità con BlueXP"].



.Fasi
. Aprire un browser Web e immettere il seguente URL:
+
https://_ipaddress_[]

+
_Ipaddress_ può essere localhost, un indirizzo IP privato o un indirizzo IP pubblico, a seconda della configurazione dell'host in cui è stato installato il connettore. Ad esempio, potrebbe essere necessario inserire un indirizzo IP privato da un host connesso all'host del connettore.

. Immettere il nome utente e la password per accedere.


.Risultato
Ora hai effettuato l'accesso e puoi iniziare a utilizzare BlueXP per gestire la tua infrastruttura multi-cloud ibrida.

--
.Modalità privata
--
Quando si utilizza BlueXP in modalità privata, è necessario accedere alla console BlueXP dall'interfaccia utente che viene eseguita localmente sul connettore.

.A proposito di questa attività
La modalità privata supporta la gestione e l'accesso degli utenti locali. L'autenticazione non viene fornita attraverso il servizio cloud di BlueXP.

.Fasi
. Aprire un browser Web e immettere il seguente URL:
+
https://_ipaddress_[]

+
_Ipaddress_ può essere localhost, un indirizzo IP privato o un indirizzo IP pubblico, a seconda della configurazione dell'host in cui è stato installato il connettore. Ad esempio, potrebbe essere necessario inserire un indirizzo IP privato da un host connesso all'host del connettore.

. Immettere il nome utente e la password per accedere.


.Risultato
Ora hai effettuato l'accesso e puoi iniziare a utilizzare BlueXP per gestire la tua infrastruttura multi-cloud ibrida.

--
====