= Aggiornamento del connettore 3.9.49
:allow-uri-read: 




=== Aggiornamento del connettore 3.9.49



==== Accesso a Gestione di sistema di ONTAP quando BlueXP  utilizza un connettore

Un amministratore di BlueXP  (utenti con il ruolo di amministratore dell'organizzazione) può configurare BlueXP  in modo che richieda agli utenti di immettere le proprie credenziali ONTAP per accedere a Gestione di sistema di ONTAP. Quando questa impostazione è attivata, gli utenti devono immettere le proprie credenziali ONTAP ogni volta che non vengono memorizzate in BlueXP .

Questa funzione è disponibile nella versione del connettore 3.9.49 e successive. link:https://docs.netapp.com/us-en/bluexp-setup-admin//task-ontap-access-connector.html["Informazioni su come configurare le impostazioni delle credenziali."^].



=== Aggiornamento del connettore 3.9.48



==== Possibilità di disattivare l'impostazione di aggiornamento automatico per il connettore

È possibile disattivare la funzione di aggiornamento automatico del connettore.

Quando si utilizza BlueXP  in modalità standard o limitata, BlueXP  aggiorna automaticamente il connettore all'ultima versione, purché disponga dell'accesso a Internet in uscita per ottenere l'aggiornamento software. Se è necessario gestire manualmente quando il connettore viene aggiornato, è ora possibile disattivare gli aggiornamenti automatici per la modalità standard o limitata.


NOTE: Questa modifica non influisce sulla modalità privata BlueXP , in cui è necessario aggiornare sempre il connettore.

Questa funzione è disponibile nella versione del connettore 3.9.48 e successive.

link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-upgrade-connector.html["Scopri come disattivare l'aggiornamento automatico per il connettore."^]
