= Connettore 3.9.52
:allow-uri-read: 




=== Connettore 3.9.52

Questa versione di BlueXP  Connector include piccoli miglioramenti alla sicurezza e correzioni di bug, oltre ad alcuni aggiornamenti aggiuntivi.

A questo punto, la versione 3.9.52 è disponibile per la modalità standard e la modalità limitata.



==== Supporto di Docker 27 e Docker 28

Docker 27 e Docker 28 sono ora supportati con il connettore.



==== Cloud Volumes ONTAP

I nodi basati sulla capacità di Cloud Volumes ONTAP non si arrestano più quando il connettore non è conforme o è inattivo per più di 14 giorni. Cloud Volumes ONTAP continua a inviare messaggi di gestione eventi quando perde l'accesso al connettore. Questa modifica garantisce che Cloud Volumes ONTAP possa continuare a funzionare anche se il connettore è inattivo per un periodo di tempo prolungato. Non modifica i requisiti di conformità per il connettore.



=== Amministrazione Keystone disponibile in BlueXP 

La versione beta di NetApp Keystone in BlueXP  ha aggiunto l'accesso all'amministrazione Keystone. È possibile accedere alla pagina di registrazione per NetApp Keystone beta dalla barra di navigazione a sinistra di BlueXP .



=== Gestione delle identità e degli accessi (IAM, Identity and Access Management) di BlueXP 

Le seguenti nuove funzionalità sono disponibili in BlueXP IAM.



==== Autenticazione multifattoriale (MFA) per utenti locali

Gli utenti locali (non federati e non associati a un account NetApp Support Site) possono abilitare l'autenticazione a più fattori. Gli amministratori possono gestire le impostazioni MFA degli utenti, ad esempio disattivandole temporaneamente o rimuovendole quando necessario.
