= Connessione alle reti di destinazione
:allow-uri-read: 


Configura la tua rete in modo che il connettore possa gestire risorse e processi all'interno del tuo ambiente di cloud pubblico. Oltre a disporre di una rete virtuale e di una subnet per il connettore, è necessario assicurarsi che siano soddisfatti i seguenti requisiti.



=== Connessione alle reti di destinazione

Un connettore richiede una connessione di rete al tipo di ambiente di lavoro che si sta creando e ai servizi che si intende abilitare.

Ad esempio, se si installa un connettore nella rete aziendale, è necessario impostare una connessione VPN alla rete virtuale in cui si avvia Cloud Volumes ONTAP.



=== Accesso a Internet in uscita

Il connettore richiede l'accesso a Internet in uscita per gestire risorse e processi all'interno del tuo ambiente di cloud pubblico.

[cols="2*"]
|===
| Endpoint | Scopo 


| https://support.netapp.com | Per ottenere informazioni sulle licenze e inviare messaggi AutoSupport al supporto NetApp. 


 a| 
https://*.api.bluexp.netapp.com

https://api.bluexp.netapp.com

https://*.cloudmanager.cloud.netapp.com

https://cloudmanager.cloud.netapp.com
 a| 
Fornire funzionalità e servizi SaaS all'interno di BlueXP.


NOTE: Il connettore sta attualmente contattando "cloudmanager.cloud.netapp.com", ma inizierà a contattare "api.bluexp.netapp.com" in una versione successiva.



| https://cloudmanagerinfraprod.azurecr.io https://*.blob.core.windows.net | Per aggiornare il connettore e i relativi componenti Docker. 


 a| 
Servizi AWS (amazonaws.com):

* CloudFormation
* Elastic Compute Cloud (EC2)
* Servizio di gestione delle chiavi (KMS)
* Servizio token di sicurezza (STS)
* S3 (Simple Storage Service)

| Per gestire le risorse in AWS. L'endpoint esatto dipende dalla regione in cui viene implementato il connettore. https://docs.aws.amazon.com/general/latest/gr/rande.html["Per ulteriori informazioni, fare riferimento alla documentazione AWS"^] 


| https://management.azure.com https://login.microsoftonline.com https://blob.core.windows.net https://core.windows.net | Per gestire le risorse nelle aree pubbliche di Azure. 


| https://management.usgovcloudapi.net https://login.microsoftonline.us https://blob.core.usgovcloudapi.net https://core.usgovcloudapi.net | Per gestire le risorse nelle regioni governative di Azure. 


| https://management.azure.microsoft.scloud https://login.microsoftonline.microsoft.scloud https://blob.core.microsoft.scloud https://core.microsoft.scloud | Per gestire le risorse nell'area Azure IL6. 


| https://management.chinacloudapi.cn https://login.chinacloudapi.cn https://blob.core.chinacloudapi.cn https://core.chinacloudapi.cn | Per gestire le risorse nelle regioni Azure China. 


| https://www.googleapis.com/compute/v1/ https://compute.googleapis.com/compute/v1 https://cloudresourcemanager.googleapis.com/v1/projects https://www.googleapis.com/compute/beta https://storage.googleapis.com/storage/v1 https://www.googleapis.com/storage/v1 https://iam.googleapis.com/v1 https://cloudkms.googleapis.com/v1 https://www.googleapis.com/deploymentmanager/v2/projects | Per gestire le risorse in Google Cloud. 
|===


=== Server proxy

Se l'organizzazione richiede la distribuzione di un server proxy per tutto il traffico Internet in uscita, ottenere le seguenti informazioni sul proxy HTTP o HTTPS:

* Indirizzo IP
* Credenziali
* Certificato HTTPS




=== Gruppo di sicurezza

Non c'è traffico in entrata verso il connettore, a meno che non venga avviato o se il connettore viene utilizzato come proxy per i messaggi AutoSupport. HTTP e HTTPS forniscono l'accesso a https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#the-local-user-interface["UI locale"], che utilizzerai in rare circostanze. SSH è necessario solo se è necessario connettersi all'host per la risoluzione dei problemi.



=== Limitazione dell'indirizzo IP

È possibile che vi sia un conflitto con gli indirizzi IP nell'intervallo 172. https://docs.netapp.com/us-en/bluexp-setup-admin/reference-limitations.html["Scopri di più su questo limite"].
