= 
:allow-uri-read: 


Creare un ruolo e applicarlo a un account di servizio da utilizzare per l'istanza della macchina virtuale del connettore.

.Fasi
. Creare un ruolo personalizzato in Google Cloud:
+
.. Creare un file YAML che includa le autorizzazioni definite in link:reference-permissions-gcp.html["Policy di Connector per Google Cloud"].
.. Da Google Cloud, attiva la shell cloud.
.. Caricare il file YAML che include le autorizzazioni richieste per il connettore.
.. Creare un ruolo personalizzato utilizzando `gcloud iam roles create` comando.
+
Nell'esempio seguente viene creato un ruolo denominato "Connector" a livello di progetto:

+
[source, gcloud]
----
gcloud iam roles create connector --project=myproject --file=connector.yaml
----
+
https://cloud.google.com/iam/docs/creating-custom-roles#iam-custom-roles-create-gcloud["Documenti Google Cloud: Creazione e gestione di ruoli personalizzati"^]



. Creare un account di servizio in Google Cloud:
+
.. Dal servizio IAM & Admin, selezionare *account di servizio > Crea account di servizio*.
.. Inserire i dettagli dell'account del servizio e selezionare *Crea e continua*.
.. Selezionare il ruolo appena creato.
.. Completare i passaggi rimanenti per creare il ruolo.
+
https://cloud.google.com/iam/docs/creating-managing-service-accounts#creating_a_service_account["Documenti Google Cloud: Creazione di un account di servizio"^]





.Risultato
A questo punto si dispone di un account di servizio che è possibile assegnare all'istanza della macchina virtuale di Connector.
