= 
:allow-uri-read: 


.Prima di iniziare
Dovresti disporre di quanto segue:

* Privilegi root per installare il connettore.
* Dettagli su un server proxy, se è richiesto un proxy per l'accesso a Internet dal connettore.
+
È possibile configurare un server proxy dopo l'installazione, ma per farlo è necessario riavviare il connettore.

+
BlueXP non supporta i server proxy trasparenti.

* Un certificato firmato dalla CA, se il server proxy utilizza HTTPS o se il proxy è un proxy di intercettazione.


.A proposito di questa attività
Il programma di installazione disponibile sul NetApp Support Site potrebbe essere una versione precedente. Dopo l'installazione, il connettore si aggiorna automaticamente se è disponibile una nuova versione.

.Fasi
. Se le variabili di sistema _http_proxy_ o _https_proxy_ sono impostate sull'host, rimuoverle:
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
Se non si rimuovono queste variabili di sistema, l'installazione avrà esito negativo.

. Scaricare il software del connettore da https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["Sito di supporto NetApp"^], Quindi copiarlo sull'host Linux.
+
È necessario scaricare il programma di installazione del connettore "online" da utilizzare nella rete o nel cloud. Un programma di installazione "offline" separato è disponibile per il connettore, ma è supportato solo con le implementazioni in modalità privata.

. Assegnare le autorizzazioni per eseguire lo script.
+
[source, cli]
----
chmod +x BlueXP-Connector-Cloud-<version>
----
+
Dove <version> è la versione del connettore scaricato.

. Eseguire lo script di installazione.
+
[source, cli]
----
 ./BlueXP-Connector-Cloud-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
I parametri --proxy e --cakert sono facoltativi. Se si dispone di un server proxy, è necessario immettere i parametri come mostrato. Il programma di installazione non richiede di fornire informazioni su un proxy.

+
Ecco un esempio del comando che utilizza entrambi i parametri facoltativi:

+
[source, cli]
----
 ./BlueXP-Connector-Cloud-v3.9.40--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
--proxy configura il connettore per l'utilizzo di un server proxy HTTP o HTTPS utilizzando uno dei seguenti formati:

+
** \http://address:port
** \http://user-name:password@address:port
** \http://domain-name%92user-name:password@address:port
** \https://address:port
** \https://user-name:password@address:port
** \https://domain-name%92user-name:password@address:port
+
Tenere presente quanto segue:

+
*** L'utente può essere un utente locale o un utente di dominio.
*** Per un utente di dominio, è necessario utilizzare il codice ASCII per un \ come mostrato sopra.
*** BlueXP non supporta nomi utente o password che includono il carattere @.
*** Se la password include uno dei seguenti caratteri speciali, è necessario uscire da quel carattere speciale prependolo con una barra rovesciata: & O !
+
Ad esempio:

+
\http://bxpproxyuser:netapp1\!@address:3128





+
--cakert specifica un certificato firmato da CA da utilizzare per l'accesso HTTPS tra il connettore e il server proxy. Questo parametro è necessario solo se si specifica un server proxy HTTPS o se il proxy è un proxy di intercettazione.



. Attendere il completamento dell'installazione.
+
Al termine dell'installazione, il servizio di connessione (occm) viene riavviato due volte se si specifica un server proxy.

. Aprire un browser Web da un host connesso alla macchina virtuale Connector e immettere il seguente URL:
+
https://_ipaddress_[]

. Dopo aver effettuato l'accesso, configurare il connettore:
+
.. Specificare l'organizzazione BlueXP  da associare al connettore.
.. Immettere un nome per il sistema.
.. In *stai eseguendo in un ambiente protetto?* Mantieni disattivata la modalità limitata.
+
La modalità limitata deve essere disattivata perché questa procedura descrive come utilizzare BlueXP in modalità standard. Attivare la modalità limitata solo se si dispone di un ambiente sicuro e si desidera disconnettere questo account dai servizi di back-end BlueXP. In tal caso, link:task-quick-start-restricted-mode.html["Segui i passaggi per iniziare a utilizzare BlueXP in modalità limitata"].

.. Selezionare *Let's start*.




.Risultato
Il connettore è ora installato e configurato con l'organizzazione BlueXP .
