= 
:allow-uri-read: 


A seconda del sistema operativo in uso, prima di installare il connettore è necessario utilizzare Podman o Docker Engine.

* Podman è necessario per Red Hat Enterprise Linux 8 e 9.
+
<<podman-versions,Visualizza le versioni di Podman supportate da BlueXP >>.

* Docker Engine è richiesto per Ubuntu.
+
<<podman-versions,Consulta le versioni di Docker Engine supportate da BlueXP >>.



.Fasi
[role="tabbed-block"]
====
.Podman
--
Per installare Podman e configurarlo in modo che soddisfi i seguenti requisiti, procedere come segue:

* Abilita e avvia il servizio podman.socket
* Installare python3
* Installa il pacchetto podman-compose versione 1.0.6
* Aggiungere podman-compose alla variabile d'ambiente PATH



NOTE: Quando si utilizza Podman, modificare la porta del servizio aardvark-dns (predefinita: 53) dopo l'installazione del connettore per evitare conflitti con la porta DNS sull'host. Seguire le istruzioni per configurare la porta.

.Fasi
. Rimuovere il pacchetto podman-docker se è installato sull'host.
+
[source, cli]
----
dnf remove podman-docker
rm /var/run/docker.sock
----
. Installa Podman.
+
Podman è disponibile presso i repository ufficiali di Red Hat Enterprise Linux.

+
Per Red Hat Enterprise Linux 9:

+
[source, cli]
----
sudo dnf install podman-2:<version>
----
+
Dove <version> è la versione supportata di Podman che stai installando. <<podman-versions,Visualizza le versioni di Podman supportate da BlueXP >>.

+
Per Red Hat Enterprise Linux 8:

+
[source, cli]
----
sudo dnf install podman-3:<version>
----
+
Dove <version> è la versione supportata di Podman che stai installando. <<podman-versions,Visualizza le versioni di Podman supportate da BlueXP >>.

. Abilitare e avviare il servizio podman.socket.
+
[source, cli]
----
sudo systemctl enable --now podman.socket
----
. Installare python3.
+
[source, cli]
----
sudo dnf install python3
----
. Installare il pacchetto repository EPEL se non è già disponibile sul sistema.
+
Questo passaggio è necessario perché podman-compose è disponibile nel repository Extra Packages for Enterprise Linux (EPEL).

+
Per Red Hat Enterprise Linux 9:

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
----
+
Per Red Hat Enterprise Linux 8:

+
[source, cli]
----
sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
----
. Installare il pacchetto podman-Compose 1,0.6.
+
[source, cli]
----
sudo dnf install podman-compose-1.0.6
----
+

NOTE: Utilizzando il `dnf install` Il comando soddisfa il requisito per aggiungere podman-compose alla variabile di ambiente PATH. Il comando di installazione aggiunge podman-componete a /usr/bin, che è già incluso in `secure_path` sull'host.



--
.Motore Docker
--
Segui la documentazione di Docker per installare Docker Engine.

.Fasi
. https://docs.docker.com/engine/install/["Consulta le istruzioni di installazione di Docker"^]
+
Assicurati di seguire la procedura per installare una versione specifica di Docker Engine. L'installazione della versione più recente installerà una versione di Docker che BlueXP non supporta.

. Verifica che Docker sia abilitato e in esecuzione.
+
[source, cli]
----
sudo systemctl enable docker && sudo systemctl start docker
----


--
====